// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_data_stream_V_dout,
        p_src_data_stream_V_empty_n,
        p_src_data_stream_V_read,
        p_dst_data_stream_V_din,
        p_dst_data_stream_V_full_n,
        p_dst_data_stream_V_write,
        p_kernel_val_0_V_1_read,
        p_kernel_val_0_V_2_read,
        p_kernel_val_1_V_0_read,
        p_kernel_val_1_V_2_read,
        p_kernel_val_2_V_0_read,
        p_kernel_val_2_V_1_read
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state9 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] p_src_data_stream_V_dout;
input   p_src_data_stream_V_empty_n;
output   p_src_data_stream_V_read;
output  [7:0] p_dst_data_stream_V_din;
input   p_dst_data_stream_V_full_n;
output   p_dst_data_stream_V_write;
input  [1:0] p_kernel_val_0_V_1_read;
input  [1:0] p_kernel_val_0_V_2_read;
input  [2:0] p_kernel_val_1_V_0_read;
input  [3:0] p_kernel_val_1_V_2_read;
input  [1:0] p_kernel_val_2_V_0_read;
input  [2:0] p_kernel_val_2_V_1_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_V_read;
reg p_dst_data_stream_V_write;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond460_i_reg_1419;
reg   [0:0] exitcond460_i_reg_1419_pp0_iter1_reg;
reg   [0:0] or_cond_i_i_reg_1428;
reg   [0:0] or_cond_i_i_reg_1428_pp0_iter1_reg;
reg   [0:0] icmp_reg_1384;
reg   [0:0] tmp_s_reg_1375;
reg    p_dst_data_stream_V_blk_n;
reg    ap_enable_reg_pp0_iter5;
reg   [0:0] or_cond_i_reg_1449;
reg   [0:0] or_cond_i_reg_1449_pp0_iter4_reg;
reg   [10:0] t_V_2_reg_323;
wire  signed [9:0] tmp_369_0_1_cast_fu_334_p1;
reg  signed [9:0] tmp_369_0_1_cast_reg_1336;
wire  signed [9:0] tmp_369_0_2_cast_fu_338_p1;
reg  signed [9:0] tmp_369_0_2_cast_reg_1341;
wire  signed [10:0] tmp_369_1_cast_fu_342_p1;
reg  signed [10:0] tmp_369_1_cast_reg_1346;
wire   [11:0] tmp_369_1_2_cast_fu_346_p1;
reg   [11:0] tmp_369_1_2_cast_reg_1351;
wire  signed [9:0] tmp_369_2_cast_fu_350_p1;
reg  signed [9:0] tmp_369_2_cast_reg_1356;
wire   [10:0] tmp_369_2_1_cast_fu_354_p1;
reg   [10:0] tmp_369_2_1_cast_reg_1361;
wire   [0:0] exitcond461_i_fu_362_p2;
wire    ap_CS_fsm_state2;
wire   [10:0] i_V_fu_368_p2;
reg   [10:0] i_V_reg_1370;
wire   [0:0] tmp_s_fu_374_p2;
wire   [0:0] tmp_284_0_not_fu_380_p2;
reg   [0:0] tmp_284_0_not_reg_1379;
wire   [0:0] icmp_fu_396_p2;
wire   [0:0] tmp_2_fu_402_p2;
reg   [0:0] tmp_2_reg_1389;
wire   [0:0] tmp_328_1_fu_408_p2;
reg   [0:0] tmp_328_1_reg_1393;
wire   [0:0] tmp_3_fu_414_p2;
reg   [0:0] tmp_3_reg_1397;
wire   [1:0] row_assign_10_0_t_fu_568_p2;
reg   [1:0] row_assign_10_0_t_reg_1404;
wire   [1:0] row_assign_10_1_t_fu_606_p2;
reg   [1:0] row_assign_10_1_t_reg_1409;
wire   [1:0] row_assign_10_2_t_fu_644_p2;
reg   [1:0] row_assign_10_2_t_reg_1414;
wire   [0:0] exitcond460_i_fu_654_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state3_pp0_stage0_iter0;
wire    ap_block_state4_pp0_stage0_iter1;
reg    ap_predicate_op161_read_state5;
reg    ap_predicate_op172_read_state5;
reg    ap_block_state5_pp0_stage0_iter2;
wire    ap_block_state6_pp0_stage0_iter3;
wire    ap_block_state7_pp0_stage0_iter4;
reg    ap_block_state8_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond460_i_reg_1419_pp0_iter2_reg;
wire   [10:0] j_V_fu_660_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_i_i_fu_712_p2;
wire  signed [13:0] x_fu_790_p3;
reg  signed [13:0] x_reg_1432;
wire   [1:0] tmp_73_fu_798_p1;
reg   [1:0] tmp_73_reg_1437;
wire   [0:0] brmerge_fu_802_p2;
reg   [0:0] brmerge_reg_1442;
reg   [0:0] brmerge_reg_1442_pp0_iter1_reg;
wire   [0:0] or_cond_i_fu_807_p2;
reg   [0:0] or_cond_i_reg_1449_pp0_iter1_reg;
reg   [0:0] or_cond_i_reg_1449_pp0_iter2_reg;
reg   [0:0] or_cond_i_reg_1449_pp0_iter3_reg;
reg   [10:0] k_buf_0_val_3_addr_reg_1453;
wire   [1:0] col_assign_3_t_fu_822_p2;
reg   [1:0] col_assign_3_t_reg_1459;
reg   [10:0] k_buf_0_val_4_addr_reg_1466;
reg   [10:0] k_buf_0_val_5_addr_reg_1472;
wire   [7:0] src_kernel_win_0_va_23_fu_946_p3;
reg   [7:0] src_kernel_win_0_va_23_reg_1478;
wire   [7:0] src_kernel_win_0_va_24_fu_964_p3;
reg   [7:0] src_kernel_win_0_va_24_reg_1485;
wire   [7:0] src_kernel_win_0_va_25_fu_982_p3;
reg   [7:0] src_kernel_win_0_va_25_reg_1491;
wire  signed [10:0] grp_fu_1245_p3;
reg  signed [10:0] sum_V_0_1_reg_1496;
wire   [11:0] sum_V_1_1_fu_1061_p2;
reg   [11:0] sum_V_1_1_reg_1501;
wire   [11:0] r_V_50_1_2_fu_1070_p2;
reg   [11:0] r_V_50_1_2_reg_1506;
wire   [7:0] tmp_79_fu_1094_p1;
reg   [7:0] tmp_79_reg_1511;
wire   [10:0] tmp4_fu_1124_p2;
reg   [10:0] tmp4_reg_1516;
wire   [7:0] tmp6_fu_1130_p2;
reg   [7:0] tmp6_reg_1521;
wire   [7:0] tmp8_fu_1136_p2;
reg   [7:0] tmp8_reg_1526;
wire   [7:0] p_Val2_6_fu_1237_p3;
reg   [7:0] p_Val2_6_reg_1531;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter3;
reg    ap_condition_pp0_exit_iter2_state5;
reg    ap_enable_reg_pp0_iter4;
wire   [10:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
wire   [10:0] k_buf_0_val_3_address1;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [10:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
wire   [10:0] k_buf_0_val_4_address1;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [10:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
wire   [10:0] k_buf_0_val_5_address1;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
reg   [10:0] t_V_reg_312;
wire    ap_CS_fsm_state9;
wire   [63:0] tmp_23_fu_815_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_150;
reg   [7:0] src_kernel_win_0_va_18_fu_154;
reg   [7:0] src_kernel_win_0_va_19_fu_158;
reg   [7:0] src_kernel_win_0_va_20_fu_162;
reg   [7:0] src_kernel_win_0_va_21_fu_166;
reg   [7:0] src_kernel_win_0_va_22_fu_170;
reg   [7:0] right_border_buf_0_s_fu_174;
wire   [7:0] col_buf_0_val_0_0_fu_856_p3;
reg   [7:0] right_border_buf_0_14_fu_178;
reg   [7:0] right_border_buf_0_15_fu_182;
reg   [7:0] right_border_buf_0_16_fu_186;
wire   [7:0] col_buf_0_val_1_0_fu_874_p3;
reg   [7:0] right_border_buf_0_17_fu_190;
reg   [7:0] right_border_buf_0_18_fu_194;
wire   [7:0] col_buf_0_val_2_0_fu_892_p3;
wire   [9:0] tmp_55_fu_386_p4;
wire   [11:0] t_V_cast_fu_358_p1;
wire   [11:0] tmp_7_fu_424_p2;
wire   [0:0] tmp_57_fu_430_p3;
wire   [0:0] tmp_10_fu_444_p2;
wire   [0:0] rev_fu_438_p2;
wire   [0:0] tmp_58_fu_456_p3;
wire   [11:0] p_assign_7_fu_464_p2;
wire   [11:0] p_p2_i497_i_fu_470_p3;
wire   [11:0] p_assign_6_1_fu_488_p2;
wire   [11:0] p_assign_6_2_fu_514_p2;
wire   [1:0] tmp_59_fu_484_p1;
wire   [0:0] tmp_13_fu_478_p2;
wire   [1:0] tmp_28_fu_540_p2;
wire   [1:0] tmp_56_fu_420_p1;
wire   [0:0] or_cond_i496_i_fu_450_p2;
wire   [1:0] tmp_30_fu_554_p2;
wire   [1:0] tmp_29_fu_546_p3;
wire   [1:0] tmp_31_fu_560_p3;
wire   [1:0] tmp_62_fu_510_p1;
wire   [0:0] tmp_61_fu_502_p3;
wire   [1:0] tmp_66_fu_580_p2;
wire   [1:0] tmp_67_fu_586_p1;
wire   [0:0] tmp_60_fu_494_p3;
wire   [1:0] tmp_41_fu_590_p3;
wire   [1:0] tmp_33_fu_574_p2;
wire   [1:0] tmp_35_fu_598_p3;
wire   [1:0] tmp_65_fu_536_p1;
wire   [0:0] tmp_64_fu_528_p3;
wire   [1:0] tmp_68_fu_618_p2;
wire   [1:0] tmp_69_fu_624_p1;
wire   [0:0] tmp_63_fu_520_p3;
wire   [1:0] tmp_42_fu_628_p3;
wire   [1:0] tmp_37_fu_612_p2;
wire   [1:0] tmp_39_fu_636_p3;
wire   [9:0] tmp_70_fu_666_p4;
wire   [11:0] t_V_2_cast_fu_650_p1;
wire  signed [11:0] ImagLoc_x_fu_682_p2;
wire   [0:0] tmp_71_fu_692_p3;
wire   [0:0] tmp_19_fu_706_p2;
wire   [0:0] rev3_fu_700_p2;
wire   [0:0] tmp_72_fu_718_p3;
wire   [11:0] p_assign_1_fu_726_p2;
wire  signed [11:0] p_p2_i_i_fu_732_p3;
wire  signed [12:0] p_p2_i_i_cast_fu_744_p1;
wire  signed [12:0] ImagLoc_x_cast_fu_688_p1;
wire   [12:0] p_assign_2_fu_754_p2;
wire   [12:0] p_assign_3_fu_760_p3;
wire   [0:0] tmp_19_not_fu_772_p2;
wire   [0:0] tmp_21_fu_748_p2;
wire   [0:0] sel_tmp7_fu_778_p2;
wire   [0:0] sel_tmp8_fu_784_p2;
wire  signed [13:0] p_p2_i_i_cast1_fu_740_p1;
wire   [13:0] sel_tmp_cast_fu_768_p1;
wire   [0:0] icmp2_fu_676_p2;
wire  signed [31:0] col_assign_cast_fu_812_p1;
wire   [7:0] tmp_24_fu_845_p5;
wire   [7:0] tmp_25_fu_863_p5;
wire   [7:0] tmp_26_fu_881_p5;
wire   [7:0] tmp_32_fu_935_p5;
wire   [7:0] tmp_36_fu_953_p5;
wire   [7:0] tmp_40_fu_971_p5;
wire   [8:0] r_V_0_cast_fu_995_p1;
wire  signed [8:0] r_V_s_fu_999_p2;
wire  signed [10:0] grp_fu_1252_p3;
wire  signed [2:0] r_V_50_1_fu_1045_p0;
wire   [7:0] r_V_50_1_fu_1045_p1;
wire  signed [10:0] r_V_50_1_fu_1045_p2;
wire  signed [11:0] tmp_370_1_cast_cast_fu_1050_p1;
wire  signed [11:0] sum_V_0_2_cast_fu_1038_p1;
wire   [3:0] r_V_50_1_2_fu_1070_p0;
wire   [7:0] r_V_50_1_2_fu_1070_p1;
wire   [7:0] tmp_77_fu_1058_p1;
wire   [7:0] tmp_76_fu_1054_p1;
wire  signed [1:0] r_V_50_2_fu_1089_p0;
wire   [7:0] r_V_50_2_fu_1089_p1;
wire   [9:0] r_V_50_2_fu_1089_p2;
wire   [2:0] r_V_50_2_1_fu_1102_p0;
wire   [7:0] r_V_50_2_1_fu_1102_p1;
wire   [10:0] r_V_50_2_1_fu_1102_p2;
wire   [9:0] tmp_370_2_2_cast_cas_fu_1111_p1;
wire   [9:0] tmp5_fu_1114_p2;
wire  signed [10:0] tmp5_cast_fu_1120_p1;
wire   [7:0] tmp_43_fu_1079_p2;
wire   [7:0] tmp_78_fu_1075_p1;
wire   [7:0] tmp_80_fu_1107_p1;
wire   [11:0] tmp3_fu_1165_p2;
wire  signed [11:0] tmp4_cast_fu_1169_p1;
wire   [11:0] p_Val2_s_fu_1172_p2;
wire   [7:0] tmp7_fu_1186_p2;
wire   [0:0] p_Result_s_fu_1178_p3;
wire   [3:0] tmp_44_fu_1195_p4;
wire   [0:0] not_i_i_fu_1211_p2;
wire   [0:0] tmp_i_i_fu_1205_p2;
wire   [0:0] overflow_fu_1217_p2;
wire   [0:0] tmp_1_i_i_fu_1231_p2;
wire   [7:0] p_mux_i_i_cast_fu_1223_p3;
wire   [7:0] p_Val2_1_fu_1190_p2;
wire  signed [1:0] grp_fu_1245_p0;
wire   [7:0] grp_fu_1245_p1;
wire  signed [1:0] grp_fu_1252_p0;
wire   [7:0] grp_fu_1252_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_block_pp0;
reg    ap_enable_operation_135;
reg    ap_enable_state4_pp0_iter1_stage0;
reg    ap_enable_operation_152;
reg    ap_enable_state5_pp0_iter2_stage0;
reg    ap_predicate_op166_store_state5;
reg    ap_enable_operation_166;
reg    ap_predicate_op173_store_state5;
reg    ap_enable_operation_173;
reg    ap_enable_operation_138;
reg    ap_enable_operation_155;
reg    ap_predicate_op164_store_state5;
reg    ap_enable_operation_164;
reg    ap_predicate_op171_store_state5;
reg    ap_enable_operation_171;
reg    ap_predicate_op140_load_state4;
reg    ap_enable_operation_140;
reg    ap_predicate_op158_load_state5;
reg    ap_enable_operation_158;
reg    ap_predicate_op162_store_state5;
reg    ap_enable_operation_162;
reg    ap_predicate_op170_store_state5;
reg    ap_enable_operation_170;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [9:0] grp_fu_1245_p10;
wire   [9:0] grp_fu_1252_p10;
wire   [11:0] r_V_50_1_2_fu_1070_p10;
wire   [10:0] r_V_50_1_fu_1045_p10;
wire   [10:0] r_V_50_2_1_fu_1102_p10;
wire   [9:0] r_V_50_2_fu_1089_p10;
reg    ap_condition_1006;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_address1),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_V_dout)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_address1),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_1_k_buf_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1920 ),
    .AddressWidth( 11 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_address1),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

sobel_hls_mux_32_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_hls_mux_32_hbi_U54(
    .din0(right_border_buf_0_s_fu_174),
    .din1(right_border_buf_0_14_fu_178),
    .din2(8'd0),
    .din3(col_assign_3_t_reg_1459),
    .dout(tmp_24_fu_845_p5)
);

sobel_hls_mux_32_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_hls_mux_32_hbi_U55(
    .din0(right_border_buf_0_16_fu_186),
    .din1(right_border_buf_0_17_fu_190),
    .din2(8'd0),
    .din3(col_assign_3_t_reg_1459),
    .dout(tmp_25_fu_863_p5)
);

sobel_hls_mux_32_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_hls_mux_32_hbi_U56(
    .din0(right_border_buf_0_18_fu_194),
    .din1(right_border_buf_0_15_fu_182),
    .din2(8'd0),
    .din3(col_assign_3_t_reg_1459),
    .dout(tmp_26_fu_881_p5)
);

sobel_hls_mux_32_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_hls_mux_32_hbi_U57(
    .din0(col_buf_0_val_0_0_fu_856_p3),
    .din1(col_buf_0_val_1_0_fu_874_p3),
    .din2(col_buf_0_val_2_0_fu_892_p3),
    .din3(row_assign_10_0_t_reg_1404),
    .dout(tmp_32_fu_935_p5)
);

sobel_hls_mux_32_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_hls_mux_32_hbi_U58(
    .din0(col_buf_0_val_0_0_fu_856_p3),
    .din1(col_buf_0_val_1_0_fu_874_p3),
    .din2(col_buf_0_val_2_0_fu_892_p3),
    .din3(row_assign_10_1_t_reg_1409),
    .dout(tmp_36_fu_953_p5)
);

sobel_hls_mux_32_hbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_hls_mux_32_hbi_U59(
    .din0(col_buf_0_val_0_0_fu_856_p3),
    .din1(col_buf_0_val_1_0_fu_874_p3),
    .din2(col_buf_0_val_2_0_fu_892_p3),
    .din3(row_assign_10_2_t_reg_1414),
    .dout(tmp_40_fu_971_p5)
);

sobel_hls_mac_mulpcA #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 9 ),
    .dout_WIDTH( 11 ))
sobel_hls_mac_mulpcA_U60(
    .din0(grp_fu_1245_p0),
    .din1(grp_fu_1245_p1),
    .din2(r_V_s_fu_999_p2),
    .dout(grp_fu_1245_p3)
);

sobel_hls_mac_mulqcK #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 11 ))
sobel_hls_mac_mulqcK_U61(
    .din0(grp_fu_1252_p0),
    .din1(grp_fu_1252_p1),
    .din2(sum_V_0_1_reg_1496),
    .dout(grp_fu_1252_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond460_i_fu_654_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond461_i_fu_362_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter2_state5)) begin
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter1;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if (((exitcond461_i_fu_362_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond460_i_fu_654_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_2_reg_323 <= j_V_fu_660_p2;
    end else if (((exitcond461_i_fu_362_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_2_reg_323 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        t_V_reg_312 <= i_V_reg_1370;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        t_V_reg_312 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond460_i_fu_654_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge_reg_1442 <= brmerge_fu_802_p2;
        or_cond_i_i_reg_1428 <= or_cond_i_i_fu_712_p2;
        or_cond_i_reg_1449 <= or_cond_i_fu_807_p2;
        tmp_73_reg_1437 <= tmp_73_fu_798_p1;
        x_reg_1432 <= x_fu_790_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge_reg_1442_pp0_iter1_reg <= brmerge_reg_1442;
        exitcond460_i_reg_1419 <= exitcond460_i_fu_654_p2;
        exitcond460_i_reg_1419_pp0_iter1_reg <= exitcond460_i_reg_1419;
        or_cond_i_i_reg_1428_pp0_iter1_reg <= or_cond_i_i_reg_1428;
        or_cond_i_reg_1449_pp0_iter1_reg <= or_cond_i_reg_1449;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond460_i_reg_1419 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        col_assign_3_t_reg_1459 <= col_assign_3_t_fu_822_p2;
        k_buf_0_val_3_addr_reg_1453 <= tmp_23_fu_815_p1;
        k_buf_0_val_4_addr_reg_1466 <= tmp_23_fu_815_p1;
        k_buf_0_val_5_addr_reg_1472 <= tmp_23_fu_815_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        exitcond460_i_reg_1419_pp0_iter2_reg <= exitcond460_i_reg_1419_pp0_iter1_reg;
        or_cond_i_reg_1449_pp0_iter2_reg <= or_cond_i_reg_1449_pp0_iter1_reg;
        or_cond_i_reg_1449_pp0_iter3_reg <= or_cond_i_reg_1449_pp0_iter2_reg;
        or_cond_i_reg_1449_pp0_iter4_reg <= or_cond_i_reg_1449_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_V_reg_1370 <= i_V_fu_368_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond461_i_fu_362_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        icmp_reg_1384 <= icmp_fu_396_p2;
        row_assign_10_0_t_reg_1404 <= row_assign_10_0_t_fu_568_p2;
        row_assign_10_1_t_reg_1409 <= row_assign_10_1_t_fu_606_p2;
        row_assign_10_2_t_reg_1414 <= row_assign_10_2_t_fu_644_p2;
        tmp_284_0_not_reg_1379 <= tmp_284_0_not_fu_380_p2;
        tmp_2_reg_1389 <= tmp_2_fu_402_p2;
        tmp_328_1_reg_1393 <= tmp_328_1_fu_408_p2;
        tmp_3_reg_1397 <= tmp_3_fu_414_p2;
        tmp_s_reg_1375 <= tmp_s_fu_374_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1449_pp0_iter3_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_Val2_6_reg_1531 <= p_Val2_6_fu_1237_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1449_pp0_iter2_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        r_V_50_1_2_reg_1506 <= r_V_50_1_2_fu_1070_p2;
        sum_V_1_1_reg_1501 <= sum_V_1_1_fu_1061_p2;
        tmp4_reg_1516 <= tmp4_fu_1124_p2;
        tmp6_reg_1521 <= tmp6_fu_1130_p2;
        tmp8_reg_1526 <= tmp8_fu_1136_p2;
        tmp_79_reg_1511 <= tmp_79_fu_1094_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_s_reg_1375 == 1'd1) & (icmp_reg_1384 == 1'd1) & (or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        right_border_buf_0_14_fu_178 <= right_border_buf_0_s_fu_174;
        right_border_buf_0_15_fu_182 <= right_border_buf_0_18_fu_194;
        right_border_buf_0_16_fu_186 <= col_buf_0_val_1_0_fu_874_p3;
        right_border_buf_0_17_fu_190 <= right_border_buf_0_16_fu_186;
        right_border_buf_0_18_fu_194 <= col_buf_0_val_2_0_fu_892_p3;
        right_border_buf_0_s_fu_174 <= col_buf_0_val_0_0_fu_856_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond460_i_reg_1419_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_18_fu_154 <= src_kernel_win_0_va_fu_150;
        src_kernel_win_0_va_19_fu_158 <= src_kernel_win_0_va_24_reg_1485;
        src_kernel_win_0_va_20_fu_162 <= src_kernel_win_0_va_19_fu_158;
        src_kernel_win_0_va_fu_150 <= src_kernel_win_0_va_23_reg_1478;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_21_fu_166 <= src_kernel_win_0_va_25_fu_982_p3;
        src_kernel_win_0_va_22_fu_170 <= src_kernel_win_0_va_21_fu_166;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_23_reg_1478 <= src_kernel_win_0_va_23_fu_946_p3;
        src_kernel_win_0_va_24_reg_1485 <= src_kernel_win_0_va_24_fu_964_p3;
        src_kernel_win_0_va_25_reg_1491 <= src_kernel_win_0_va_25_fu_982_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_1449_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sum_V_0_1_reg_1496 <= grp_fu_1245_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_369_0_1_cast_reg_1336 <= tmp_369_0_1_cast_fu_334_p1;
        tmp_369_0_2_cast_reg_1341 <= tmp_369_0_2_cast_fu_338_p1;
        tmp_369_1_2_cast_reg_1351[3 : 0] <= tmp_369_1_2_cast_fu_346_p1[3 : 0];
        tmp_369_1_cast_reg_1346 <= tmp_369_1_cast_fu_342_p1;
        tmp_369_2_1_cast_reg_1361[2 : 0] <= tmp_369_2_1_cast_fu_354_p1[2 : 0];
        tmp_369_2_cast_reg_1356 <= tmp_369_2_cast_fu_350_p1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_condition_pp0_exit_iter2_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter2_state5 = 1'b0;
    end
end

always @ (*) begin
    if ((((exitcond461_i_fu_362_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond461_i_fu_362_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1375 == 1'd1) & (icmp_reg_1384 == 1'd1) & (or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_2_reg_1389 == 1'd1) & (or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (icmp_reg_1384 == 1'd0) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1375 == 1'd1) & (icmp_reg_1384 == 1'd1) & (or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_2_reg_1389 == 1'd1) & (or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (icmp_reg_1384 == 1'd0) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1375 == 1'd1) & (icmp_reg_1384 == 1'd1) & (or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_328_1_reg_1393 == 1'd1) & (or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (icmp_reg_1384 == 1'd0) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1006)) begin
        if (((tmp_s_reg_1375 == 1'd1) & (icmp_reg_1384 == 1'd1))) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if (((tmp_328_1_reg_1393 == 1'd1) & (icmp_reg_1384 == 1'd0))) begin
            k_buf_0_val_4_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1375 == 1'd1) & (icmp_reg_1384 == 1'd1) & (or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_328_1_reg_1393 == 1'd1) & (or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (icmp_reg_1384 == 1'd0) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1375 == 1'd1) & (icmp_reg_1384 == 1'd1) & (or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_2_reg_1389 == 1'd1) & (or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (icmp_reg_1384 == 1'd0) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_1006)) begin
        if (((tmp_s_reg_1375 == 1'd1) & (icmp_reg_1384 == 1'd1))) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if (((tmp_2_reg_1389 == 1'd1) & (icmp_reg_1384 == 1'd0))) begin
            k_buf_0_val_5_d1 = p_src_data_stream_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1375 == 1'd1) & (icmp_reg_1384 == 1'd1) & (or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)) | ((tmp_2_reg_1389 == 1'd1) & (or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (icmp_reg_1384 == 1'd0) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_1449_pp0_iter4_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        p_dst_data_stream_V_blk_n = p_dst_data_stream_V_full_n;
    end else begin
        p_dst_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_1449_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_V_write = 1'b1;
    end else begin
        p_dst_data_stream_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_s_reg_1375 == 1'd1) & (icmp_reg_1384 == 1'd1) & (or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (icmp_reg_1384 == 1'd0) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        p_src_data_stream_V_blk_n = p_src_data_stream_V_empty_n;
    end else begin
        p_src_data_stream_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op172_read_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op161_read_state5 == 1'b1)))) begin
        p_src_data_stream_V_read = 1'b1;
    end else begin
        p_src_data_stream_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond461_i_fu_362_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)) & ~((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_cast_fu_688_p1 = ImagLoc_x_fu_682_p2;

assign ImagLoc_x_fu_682_p2 = ($signed(12'd4095) + $signed(t_V_2_cast_fu_650_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((or_cond_i_reg_1449_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op172_read_state5 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op161_read_state5 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((or_cond_i_reg_1449_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op172_read_state5 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op161_read_state5 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((or_cond_i_reg_1449_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op172_read_state5 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op161_read_state5 == 1'b1)))));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter2 = (((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op172_read_state5 == 1'b1)) | ((p_src_data_stream_V_empty_n == 1'b0) & (ap_predicate_op161_read_state5 == 1'b1)));
end

assign ap_block_state6_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp0_stage0_iter5 = ((or_cond_i_reg_1449_pp0_iter4_reg == 1'd1) & (p_dst_data_stream_V_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_1006 = ((or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1));
end

always @ (*) begin
    ap_enable_operation_135 = (exitcond460_i_reg_1419 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_138 = (exitcond460_i_reg_1419 == 1'd0);
end

always @ (*) begin
    ap_enable_operation_140 = (ap_predicate_op140_load_state4 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_152 = (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0);
end

always @ (*) begin
    ap_enable_operation_155 = (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0);
end

always @ (*) begin
    ap_enable_operation_158 = (ap_predicate_op158_load_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_162 = (ap_predicate_op162_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_164 = (ap_predicate_op164_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_166 = (ap_predicate_op166_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_170 = (ap_predicate_op170_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_171 = (ap_predicate_op171_store_state5 == 1'b1);
end

always @ (*) begin
    ap_enable_operation_173 = (ap_predicate_op173_store_state5 == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_enable_state4_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state5_pp0_iter2_stage0 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_predicate_op140_load_state4 = ((brmerge_reg_1442 == 1'd1) & (exitcond460_i_reg_1419 == 1'd0));
end

always @ (*) begin
    ap_predicate_op158_load_state5 = ((brmerge_reg_1442_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op161_read_state5 = ((or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (icmp_reg_1384 == 1'd0) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op162_store_state5 = ((tmp_2_reg_1389 == 1'd1) & (or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (icmp_reg_1384 == 1'd0) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op164_store_state5 = ((tmp_328_1_reg_1393 == 1'd1) & (or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (icmp_reg_1384 == 1'd0) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op166_store_state5 = ((tmp_2_reg_1389 == 1'd1) & (or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (icmp_reg_1384 == 1'd0) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op170_store_state5 = ((tmp_s_reg_1375 == 1'd1) & (icmp_reg_1384 == 1'd1) & (or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op171_store_state5 = ((tmp_s_reg_1375 == 1'd1) & (icmp_reg_1384 == 1'd1) & (or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op172_read_state5 = ((tmp_s_reg_1375 == 1'd1) & (icmp_reg_1384 == 1'd1) & (or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op173_store_state5 = ((tmp_s_reg_1375 == 1'd1) & (icmp_reg_1384 == 1'd1) & (or_cond_i_i_reg_1428_pp0_iter1_reg == 1'd1) & (exitcond460_i_reg_1419_pp0_iter1_reg == 1'd0));
end

assign brmerge_fu_802_p2 = (tmp_284_0_not_reg_1379 | tmp_19_fu_706_p2);

assign col_assign_3_t_fu_822_p2 = (tmp_73_reg_1437 ^ 2'd3);

assign col_assign_cast_fu_812_p1 = x_reg_1432;

assign col_buf_0_val_0_0_fu_856_p3 = ((brmerge_reg_1442_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_24_fu_845_p5);

assign col_buf_0_val_1_0_fu_874_p3 = ((brmerge_reg_1442_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_25_fu_863_p5);

assign col_buf_0_val_2_0_fu_892_p3 = ((brmerge_reg_1442_pp0_iter1_reg[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_26_fu_881_p5);

assign exitcond460_i_fu_654_p2 = ((t_V_2_reg_323 == 11'd1922) ? 1'b1 : 1'b0);

assign exitcond461_i_fu_362_p2 = ((t_V_reg_312 == 11'd1082) ? 1'b1 : 1'b0);

assign grp_fu_1245_p0 = tmp_369_0_1_cast_reg_1336;

assign grp_fu_1245_p1 = grp_fu_1245_p10;

assign grp_fu_1245_p10 = src_kernel_win_0_va_21_fu_166;

assign grp_fu_1252_p0 = tmp_369_0_2_cast_reg_1341;

assign grp_fu_1252_p1 = grp_fu_1252_p10;

assign grp_fu_1252_p10 = src_kernel_win_0_va_25_reg_1491;

assign i_V_fu_368_p2 = (t_V_reg_312 + 11'd1);

assign icmp2_fu_676_p2 = ((tmp_70_fu_666_p4 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_fu_396_p2 = ((tmp_55_fu_386_p4 != 10'd0) ? 1'b1 : 1'b0);

assign j_V_fu_660_p2 = (t_V_2_reg_323 + 11'd1);

assign k_buf_0_val_3_address0 = tmp_23_fu_815_p1;

assign k_buf_0_val_3_address1 = k_buf_0_val_3_addr_reg_1453;

assign k_buf_0_val_4_address0 = tmp_23_fu_815_p1;

assign k_buf_0_val_4_address1 = k_buf_0_val_4_addr_reg_1466;

assign k_buf_0_val_5_address0 = tmp_23_fu_815_p1;

assign k_buf_0_val_5_address1 = k_buf_0_val_5_addr_reg_1472;

assign not_i_i_fu_1211_p2 = ((tmp_44_fu_1195_p4 != 4'd0) ? 1'b1 : 1'b0);

assign or_cond_i496_i_fu_450_p2 = (tmp_10_fu_444_p2 & rev_fu_438_p2);

assign or_cond_i_fu_807_p2 = (icmp_reg_1384 & icmp2_fu_676_p2);

assign or_cond_i_i_fu_712_p2 = (tmp_19_fu_706_p2 & rev3_fu_700_p2);

assign overflow_fu_1217_p2 = (tmp_i_i_fu_1205_p2 & not_i_i_fu_1211_p2);

assign p_Result_s_fu_1178_p3 = p_Val2_s_fu_1172_p2[32'd11];

assign p_Val2_1_fu_1190_p2 = (tmp6_reg_1521 + tmp7_fu_1186_p2);

assign p_Val2_6_fu_1237_p3 = ((tmp_1_i_i_fu_1231_p2[0:0] === 1'b1) ? p_mux_i_i_cast_fu_1223_p3 : p_Val2_1_fu_1190_p2);

assign p_Val2_s_fu_1172_p2 = ($signed(tmp3_fu_1165_p2) + $signed(tmp4_cast_fu_1169_p1));

assign p_assign_1_fu_726_p2 = (12'd1 - t_V_2_cast_fu_650_p1);

assign p_assign_2_fu_754_p2 = ($signed(13'd3838) - $signed(p_p2_i_i_cast_fu_744_p1));

assign p_assign_3_fu_760_p3 = ((or_cond_i_i_fu_712_p2[0:0] === 1'b1) ? ImagLoc_x_cast_fu_688_p1 : p_assign_2_fu_754_p2);

assign p_assign_6_1_fu_488_p2 = ($signed(12'd4094) + $signed(t_V_cast_fu_358_p1));

assign p_assign_6_2_fu_514_p2 = ($signed(12'd4093) + $signed(t_V_cast_fu_358_p1));

assign p_assign_7_fu_464_p2 = (12'd1 - t_V_cast_fu_358_p1);

assign p_dst_data_stream_V_din = p_Val2_6_reg_1531;

assign p_mux_i_i_cast_fu_1223_p3 = ((tmp_i_i_fu_1205_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_p2_i497_i_fu_470_p3 = ((tmp_58_fu_456_p3[0:0] === 1'b1) ? p_assign_7_fu_464_p2 : tmp_7_fu_424_p2);

assign p_p2_i_i_cast1_fu_740_p1 = p_p2_i_i_fu_732_p3;

assign p_p2_i_i_cast_fu_744_p1 = p_p2_i_i_fu_732_p3;

assign p_p2_i_i_fu_732_p3 = ((tmp_72_fu_718_p3[0:0] === 1'b1) ? p_assign_1_fu_726_p2 : ImagLoc_x_fu_682_p2);

assign r_V_0_cast_fu_995_p1 = src_kernel_win_0_va_22_fu_170;

assign r_V_50_1_2_fu_1070_p0 = tmp_369_1_2_cast_reg_1351;

assign r_V_50_1_2_fu_1070_p1 = r_V_50_1_2_fu_1070_p10;

assign r_V_50_1_2_fu_1070_p10 = src_kernel_win_0_va_24_reg_1485;

assign r_V_50_1_2_fu_1070_p2 = (r_V_50_1_2_fu_1070_p0 * r_V_50_1_2_fu_1070_p1);

assign r_V_50_1_fu_1045_p0 = tmp_369_1_cast_reg_1346;

assign r_V_50_1_fu_1045_p1 = r_V_50_1_fu_1045_p10;

assign r_V_50_1_fu_1045_p10 = src_kernel_win_0_va_20_fu_162;

assign r_V_50_1_fu_1045_p2 = ($signed(r_V_50_1_fu_1045_p0) * $signed({{1'b0}, {r_V_50_1_fu_1045_p1}}));

assign r_V_50_2_1_fu_1102_p0 = tmp_369_2_1_cast_reg_1361;

assign r_V_50_2_1_fu_1102_p1 = r_V_50_2_1_fu_1102_p10;

assign r_V_50_2_1_fu_1102_p10 = src_kernel_win_0_va_fu_150;

assign r_V_50_2_1_fu_1102_p2 = (r_V_50_2_1_fu_1102_p0 * r_V_50_2_1_fu_1102_p1);

assign r_V_50_2_fu_1089_p0 = tmp_369_2_cast_reg_1356;

assign r_V_50_2_fu_1089_p1 = r_V_50_2_fu_1089_p10;

assign r_V_50_2_fu_1089_p10 = src_kernel_win_0_va_18_fu_154;

assign r_V_50_2_fu_1089_p2 = ($signed(r_V_50_2_fu_1089_p0) * $signed({{1'b0}, {r_V_50_2_fu_1089_p1}}));

assign r_V_s_fu_999_p2 = (9'd0 - r_V_0_cast_fu_995_p1);

assign rev3_fu_700_p2 = (tmp_71_fu_692_p3 ^ 1'd1);

assign rev_fu_438_p2 = (tmp_57_fu_430_p3 ^ 1'd1);

assign row_assign_10_0_t_fu_568_p2 = (tmp_31_fu_560_p3 ^ 2'd3);

assign row_assign_10_1_t_fu_606_p2 = (tmp_35_fu_598_p3 ^ 2'd3);

assign row_assign_10_2_t_fu_644_p2 = (tmp_39_fu_636_p3 ^ 2'd3);

assign sel_tmp7_fu_778_p2 = (tmp_71_fu_692_p3 | tmp_19_not_fu_772_p2);

assign sel_tmp8_fu_784_p2 = (tmp_21_fu_748_p2 & sel_tmp7_fu_778_p2);

assign sel_tmp_cast_fu_768_p1 = p_assign_3_fu_760_p3;

assign src_kernel_win_0_va_23_fu_946_p3 = ((tmp_3_reg_1397[0:0] === 1'b1) ? tmp_32_fu_935_p5 : col_buf_0_val_0_0_fu_856_p3);

assign src_kernel_win_0_va_24_fu_964_p3 = ((tmp_3_reg_1397[0:0] === 1'b1) ? tmp_36_fu_953_p5 : col_buf_0_val_1_0_fu_874_p3);

assign src_kernel_win_0_va_25_fu_982_p3 = ((tmp_3_reg_1397[0:0] === 1'b1) ? tmp_40_fu_971_p5 : col_buf_0_val_2_0_fu_892_p3);

assign sum_V_0_2_cast_fu_1038_p1 = grp_fu_1252_p3;

assign sum_V_1_1_fu_1061_p2 = ($signed(tmp_370_1_cast_cast_fu_1050_p1) + $signed(sum_V_0_2_cast_fu_1038_p1));

assign t_V_2_cast_fu_650_p1 = t_V_2_reg_323;

assign t_V_cast_fu_358_p1 = t_V_reg_312;

assign tmp3_fu_1165_p2 = (r_V_50_1_2_reg_1506 + sum_V_1_1_reg_1501);

assign tmp4_cast_fu_1169_p1 = $signed(tmp4_reg_1516);

assign tmp4_fu_1124_p2 = ($signed(r_V_50_2_1_fu_1102_p2) + $signed(tmp5_cast_fu_1120_p1));

assign tmp5_cast_fu_1120_p1 = $signed(tmp5_fu_1114_p2);

assign tmp5_fu_1114_p2 = (tmp_370_2_2_cast_cas_fu_1111_p1 + r_V_50_2_fu_1089_p2);

assign tmp6_fu_1130_p2 = (tmp_43_fu_1079_p2 + tmp_78_fu_1075_p1);

assign tmp7_fu_1186_p2 = (tmp_79_reg_1511 + tmp8_reg_1526);

assign tmp8_fu_1136_p2 = (src_kernel_win_0_va_23_reg_1478 + tmp_80_fu_1107_p1);

assign tmp_10_fu_444_p2 = (($signed(tmp_7_fu_424_p2) < $signed(12'd1080)) ? 1'b1 : 1'b0);

assign tmp_13_fu_478_p2 = (($signed(p_p2_i497_i_fu_470_p3) < $signed(12'd1080)) ? 1'b1 : 1'b0);

assign tmp_19_fu_706_p2 = (($signed(ImagLoc_x_fu_682_p2) < $signed(12'd1920)) ? 1'b1 : 1'b0);

assign tmp_19_not_fu_772_p2 = (tmp_19_fu_706_p2 ^ 1'd1);

assign tmp_1_i_i_fu_1231_p2 = (p_Result_s_fu_1178_p3 | overflow_fu_1217_p2);

assign tmp_21_fu_748_p2 = (($signed(p_p2_i_i_fu_732_p3) < $signed(12'd1920)) ? 1'b1 : 1'b0);

assign tmp_23_fu_815_p1 = $unsigned(col_assign_cast_fu_812_p1);

assign tmp_284_0_not_fu_380_p2 = (tmp_s_fu_374_p2 ^ 1'd1);

assign tmp_28_fu_540_p2 = ($signed(2'd2) - $signed(tmp_59_fu_484_p1));

assign tmp_29_fu_546_p3 = ((tmp_13_fu_478_p2[0:0] === 1'b1) ? tmp_59_fu_484_p1 : tmp_28_fu_540_p2);

assign tmp_2_fu_402_p2 = ((t_V_reg_312 == 11'd1) ? 1'b1 : 1'b0);

assign tmp_30_fu_554_p2 = ($signed(2'd3) + $signed(tmp_56_fu_420_p1));

assign tmp_31_fu_560_p3 = ((or_cond_i496_i_fu_450_p2[0:0] === 1'b1) ? tmp_30_fu_554_p2 : tmp_29_fu_546_p3);

assign tmp_328_1_fu_408_p2 = ((t_V_reg_312 == 11'd0) ? 1'b1 : 1'b0);

assign tmp_33_fu_574_p2 = (tmp_56_fu_420_p1 ^ 2'd2);

assign tmp_35_fu_598_p3 = ((tmp_60_fu_494_p3[0:0] === 1'b1) ? tmp_41_fu_590_p3 : tmp_33_fu_574_p2);

assign tmp_369_0_1_cast_fu_334_p1 = $signed(p_kernel_val_0_V_1_read);

assign tmp_369_0_2_cast_fu_338_p1 = $signed(p_kernel_val_0_V_2_read);

assign tmp_369_1_2_cast_fu_346_p1 = p_kernel_val_1_V_2_read;

assign tmp_369_1_cast_fu_342_p1 = $signed(p_kernel_val_1_V_0_read);

assign tmp_369_2_1_cast_fu_354_p1 = p_kernel_val_2_V_1_read;

assign tmp_369_2_cast_fu_350_p1 = $signed(p_kernel_val_2_V_0_read);

assign tmp_370_1_cast_cast_fu_1050_p1 = r_V_50_1_fu_1045_p2;

assign tmp_370_2_2_cast_cas_fu_1111_p1 = src_kernel_win_0_va_23_reg_1478;

assign tmp_37_fu_612_p2 = (2'd1 + tmp_56_fu_420_p1);

assign tmp_39_fu_636_p3 = ((tmp_63_fu_520_p3[0:0] === 1'b1) ? tmp_42_fu_628_p3 : tmp_37_fu_612_p2);

assign tmp_3_fu_414_p2 = ((t_V_reg_312 > 11'd1080) ? 1'b1 : 1'b0);

assign tmp_41_fu_590_p3 = ((tmp_61_fu_502_p3[0:0] === 1'b1) ? tmp_66_fu_580_p2 : tmp_67_fu_586_p1);

assign tmp_42_fu_628_p3 = ((tmp_64_fu_528_p3[0:0] === 1'b1) ? tmp_68_fu_618_p2 : tmp_69_fu_624_p1);

assign tmp_43_fu_1079_p2 = (tmp_77_fu_1058_p1 + tmp_76_fu_1054_p1);

assign tmp_44_fu_1195_p4 = {{p_Val2_s_fu_1172_p2[11:8]}};

assign tmp_55_fu_386_p4 = {{t_V_reg_312[10:1]}};

assign tmp_56_fu_420_p1 = t_V_reg_312[1:0];

assign tmp_57_fu_430_p3 = tmp_7_fu_424_p2[32'd11];

assign tmp_58_fu_456_p3 = tmp_7_fu_424_p2[32'd11];

assign tmp_59_fu_484_p1 = p_p2_i497_i_fu_470_p3[1:0];

assign tmp_60_fu_494_p3 = p_assign_6_1_fu_488_p2[32'd11];

assign tmp_61_fu_502_p3 = p_assign_6_1_fu_488_p2[32'd11];

assign tmp_62_fu_510_p1 = t_V_reg_312[1:0];

assign tmp_63_fu_520_p3 = p_assign_6_2_fu_514_p2[32'd11];

assign tmp_64_fu_528_p3 = p_assign_6_2_fu_514_p2[32'd11];

assign tmp_65_fu_536_p1 = t_V_reg_312[1:0];

assign tmp_66_fu_580_p2 = ($signed(2'd2) - $signed(tmp_62_fu_510_p1));

assign tmp_67_fu_586_p1 = p_assign_6_1_fu_488_p2[1:0];

assign tmp_68_fu_618_p2 = (tmp_65_fu_536_p1 ^ 2'd3);

assign tmp_69_fu_624_p1 = p_assign_6_2_fu_514_p2[1:0];

assign tmp_70_fu_666_p4 = {{t_V_2_reg_323[10:1]}};

assign tmp_71_fu_692_p3 = ImagLoc_x_fu_682_p2[32'd11];

assign tmp_72_fu_718_p3 = ImagLoc_x_fu_682_p2[32'd11];

assign tmp_73_fu_798_p1 = x_fu_790_p3[1:0];

assign tmp_76_fu_1054_p1 = r_V_50_1_fu_1045_p2[7:0];

assign tmp_77_fu_1058_p1 = grp_fu_1252_p3[7:0];

assign tmp_78_fu_1075_p1 = r_V_50_1_2_fu_1070_p2[7:0];

assign tmp_79_fu_1094_p1 = r_V_50_2_fu_1089_p2[7:0];

assign tmp_7_fu_424_p2 = ($signed(12'd4095) + $signed(t_V_cast_fu_358_p1));

assign tmp_80_fu_1107_p1 = r_V_50_2_1_fu_1102_p2[7:0];

assign tmp_i_i_fu_1205_p2 = (p_Result_s_fu_1178_p3 ^ 1'd1);

assign tmp_s_fu_374_p2 = ((t_V_reg_312 < 11'd1080) ? 1'b1 : 1'b0);

assign x_fu_790_p3 = ((sel_tmp8_fu_784_p2[0:0] === 1'b1) ? p_p2_i_i_cast1_fu_740_p1 : sel_tmp_cast_fu_768_p1);

always @ (posedge ap_clk) begin
    tmp_369_1_2_cast_reg_1351[11:4] <= 8'b00000000;
    tmp_369_2_1_cast_reg_1361[10:3] <= 8'b00000000;
end

endmodule //Filter2D
