// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_sobel_hls (
hls::stream<struct ap_axiu<24, 1, 1, 1 > > (&INPUT_STREAM),
hls::stream<struct ap_axiu<24, 1, 1, 1 > > (&OUTPUT_STREAM));
