-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Filter2D_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    p_src_data_stream_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    p_src_data_stream_V_empty_n : IN STD_LOGIC;
    p_src_data_stream_V_read : OUT STD_LOGIC;
    p_dst_data_stream_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_dst_data_stream_V_full_n : IN STD_LOGIC;
    p_dst_data_stream_V_write : OUT STD_LOGIC );
end;


architecture behav of Filter2D_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv10_2D2 : STD_LOGIC_VECTOR (9 downto 0) := "1011010010";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv10_2D0 : STD_LOGIC_VECTOR (9 downto 0) := "1011010000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv11_7FF : STD_LOGIC_VECTOR (10 downto 0) := "11111111111";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv11_2D0 : STD_LOGIC_VECTOR (10 downto 0) := "01011010000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv11_7FE : STD_LOGIC_VECTOR (10 downto 0) := "11111111110";
    constant ap_const_lv11_7FD : STD_LOGIC_VECTOR (10 downto 0) := "11111111101";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv11_502 : STD_LOGIC_VECTOR (10 downto 0) := "10100000010";
    constant ap_const_lv12_FFF : STD_LOGIC_VECTOR (11 downto 0) := "111111111111";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv12_500 : STD_LOGIC_VECTOR (11 downto 0) := "010100000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv12_9FE : STD_LOGIC_VECTOR (11 downto 0) := "100111111110";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv21_1171 : STD_LOGIC_VECTOR (20 downto 0) := "000000001000101110001";
    constant ap_const_lv19_3A8 : STD_LOGIC_VECTOR (18 downto 0) := "0000000001110101000";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal p_src_data_stream_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal exitcond460_i_reg_1441 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond460_i_reg_1441_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_i_reg_1450 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_i_reg_1450_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_reg_1406 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_1397 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_dst_data_stream_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal or_cond_i_reg_1471 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_reg_1471_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal t_V_2_reg_303 : STD_LOGIC_VECTOR (10 downto 0);
    signal exitcond461_i_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal i_V_fu_324_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal i_V_reg_1392 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_s_fu_330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_424_0_not_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_424_0_not_reg_1401 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_fu_352_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_358_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_1411 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_468_1_fu_364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_468_1_reg_1415 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_1419 : STD_LOGIC_VECTOR (0 downto 0);
    signal row_assign_13_0_t_fu_524_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal row_assign_13_0_t_reg_1426 : STD_LOGIC_VECTOR (1 downto 0);
    signal row_assign_13_1_t_fu_562_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal row_assign_13_1_t_reg_1431 : STD_LOGIC_VECTOR (1 downto 0);
    signal row_assign_13_2_t_fu_600_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal row_assign_13_2_t_reg_1436 : STD_LOGIC_VECTOR (1 downto 0);
    signal exitcond460_i_fu_610_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_predicate_op147_read_state5 : BOOLEAN;
    signal ap_predicate_op158_read_state5 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal exitcond460_i_reg_1441_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal j_V_fu_616_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal or_cond_i_i_fu_664_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_fu_738_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal x_reg_1454 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_43_fu_746_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_43_reg_1459 : STD_LOGIC_VECTOR (1 downto 0);
    signal brmerge_fu_750_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_reg_1464 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_reg_1464_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_fu_755_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_reg_1471_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_reg_1471_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_i_reg_1471_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal k_buf_0_val_3_addr_reg_1475 : STD_LOGIC_VECTOR (10 downto 0);
    signal col_assign_6_t_fu_770_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal col_assign_6_t_reg_1481 : STD_LOGIC_VECTOR (1 downto 0);
    signal k_buf_0_val_4_addr_reg_1488 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_5_addr_reg_1494 : STD_LOGIC_VECTOR (10 downto 0);
    signal src_kernel_win_0_va_6_fu_894_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_6_reg_1500 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_6_reg_1500_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_7_fu_912_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_7_reg_1506 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_8_fu_930_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_8_reg_1512 : STD_LOGIC_VECTOR (7 downto 0);
    signal r_V_52_1_1_fu_1278_p2 : STD_LOGIC_VECTOR (20 downto 0);
    signal r_V_52_1_1_reg_1518 : STD_LOGIC_VECTOR (20 downto 0);
    signal src_kernel_win_0_va_16_reg_1523 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_9_reg_1528 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_12_reg_1534 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1284_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal sum_V_0_2_reg_1540 : STD_LOGIC_VECTOR (24 downto 0);
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal tmp3_fu_1055_p2 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp3_reg_1545 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_Val2_s_fu_1189_p2 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Val2_s_reg_1550 : STD_LOGIC_VECTOR (26 downto 0);
    signal p_Val2_1_reg_1555 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_46_reg_1560 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_35_reg_1565 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_condition_pp0_exit_iter2_state5 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal k_buf_0_val_3_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_3_ce0 : STD_LOGIC;
    signal k_buf_0_val_3_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_3_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_3_ce1 : STD_LOGIC;
    signal k_buf_0_val_3_we1 : STD_LOGIC;
    signal k_buf_0_val_4_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_4_ce0 : STD_LOGIC;
    signal k_buf_0_val_4_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_4_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_4_ce1 : STD_LOGIC;
    signal k_buf_0_val_4_we1 : STD_LOGIC;
    signal k_buf_0_val_4_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_5_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_5_ce0 : STD_LOGIC;
    signal k_buf_0_val_5_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal k_buf_0_val_5_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal k_buf_0_val_5_ce1 : STD_LOGIC;
    signal k_buf_0_val_5_we1 : STD_LOGIC;
    signal k_buf_0_val_5_d1 : STD_LOGIC_VECTOR (7 downto 0);
    signal t_V_reg_292 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal tmp_26_fu_763_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal src_kernel_win_0_va_fu_166 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_1_fu_170 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_2_fu_174 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_3_fu_178 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_4_fu_182 : STD_LOGIC_VECTOR (7 downto 0);
    signal src_kernel_win_0_va_5_fu_186 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_s_fu_190 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_0_0_fu_804_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_1_fu_194 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_2_fu_198 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_3_fu_202 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_1_0_fu_822_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_4_fu_206 : STD_LOGIC_VECTOR (7 downto 0);
    signal right_border_buf_0_5_fu_210 : STD_LOGIC_VECTOR (7 downto 0);
    signal col_buf_0_val_2_0_fu_840_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_342_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal t_V_cast_fu_314_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_8_fu_376_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_5_fu_380_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_10_fu_392_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_fu_400_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_418_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_assign_s_fu_426_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_p2_i497_i_fu_432_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_12_fu_440_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_assign_14_1_fu_456_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal p_assign_14_2_fu_482_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_9_fu_444_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_assign_1_fu_450_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_cond_i496_i_fu_412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_72_cast_fu_386_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal p_p2_i497_i_p_assign_s_fu_508_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal y_fu_516_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_20_fu_478_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_15_fu_470_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_27_fu_536_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_29_fu_542_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_14_fu_462_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_546_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_530_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_13_fu_554_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_25_fu_504_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_24_fu_496_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_38_fu_574_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_39_fu_580_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_21_fu_488_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_584_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_16_fu_568_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_18_fu_592_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_40_fu_622_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal t_V_3_cast_fu_606_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ImagLoc_x_fu_638_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_41_fu_644_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_fu_658_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev1_fu_652_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_42_fu_670_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_assign_3_fu_678_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_p2_i_i_fu_684_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_assign_4_fu_702_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal p_assign_5_fu_708_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_26_not_fu_720_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_696_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_726_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_fu_732_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_p2_i_i_cast_fu_692_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal sel_tmp_cast_fu_716_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal icmp1_fu_632_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal col_assign_cast_fu_760_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_28_fu_793_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_30_fu_811_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_31_fu_829_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_32_fu_883_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_33_fu_901_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_34_fu_919_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_shl1_fu_971_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_shl2_fu_983_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl1_cast_fu_979_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_shl2_cast_fu_991_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal r_V_52_0_1_fu_995_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal r_V_52_0_1_cast_fu_1001_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal p_shl5_fu_1012_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_shl6_fu_1023_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl5_cast_fu_1019_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_shl6_cast_fu_1030_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal r_V_52_1_2_fu_1034_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal r_V_52_1_2_cast_fu_1040_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_1294_p3 : STD_LOGIC_VECTOR (20 downto 0);
    signal tmp_510_1_2_cast_cas_fu_1044_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp4_cast_fu_1052_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal p_shl3_fu_1092_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_shl4_fu_1103_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl3_cast_fu_1099_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_shl4_cast_fu_1110_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal r_V_52_1_fu_1114_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal r_V_52_1_cast_fu_1120_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_510_1_cast_fu_1124_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sum_V_0_2_cast_fu_1089_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp2_fu_1128_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp3_cast_fu_1134_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal sum_V_2_fu_1137_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal p_shl_fu_1147_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_shl7_fu_1158_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl_cast_fu_1154_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal p_shl7_cast_fu_1165_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal r_V_52_2_1_fu_1169_p2 : STD_LOGIC_VECTOR (19 downto 0);
    signal r_V_52_2_1_cast_fu_1175_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_1302_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal sum_V_2_cast_fu_1143_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal tmp5_cast_fu_1186_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal tmp_6_i_i_cast_fu_1223_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_47_fu_1236_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_2_fu_1226_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_48_fu_1249_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev2_fu_1243_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_fu_1231_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_carry_1_fu_1257_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_fu_1263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_V_52_1_1_fu_1278_p0 : STD_LOGIC_VECTOR (13 downto 0);
    signal r_V_52_1_1_fu_1278_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1284_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1284_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1284_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_1284_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_fu_1294_p0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_1294_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1302_p0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_1302_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_1302_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0 : BOOLEAN;
    signal ap_enable_operation_121 : BOOLEAN;
    signal ap_enable_state4_pp0_iter1_stage0 : BOOLEAN;
    signal ap_enable_operation_138 : BOOLEAN;
    signal ap_enable_state5_pp0_iter2_stage0 : BOOLEAN;
    signal ap_predicate_op152_store_state5 : BOOLEAN;
    signal ap_enable_operation_152 : BOOLEAN;
    signal ap_predicate_op159_store_state5 : BOOLEAN;
    signal ap_enable_operation_159 : BOOLEAN;
    signal ap_enable_operation_124 : BOOLEAN;
    signal ap_enable_operation_141 : BOOLEAN;
    signal ap_predicate_op150_store_state5 : BOOLEAN;
    signal ap_enable_operation_150 : BOOLEAN;
    signal ap_predicate_op157_store_state5 : BOOLEAN;
    signal ap_enable_operation_157 : BOOLEAN;
    signal ap_predicate_op126_load_state4 : BOOLEAN;
    signal ap_enable_operation_126 : BOOLEAN;
    signal ap_predicate_op144_load_state5 : BOOLEAN;
    signal ap_enable_operation_144 : BOOLEAN;
    signal ap_predicate_op148_store_state5 : BOOLEAN;
    signal ap_enable_operation_148 : BOOLEAN;
    signal ap_predicate_op156_store_state5 : BOOLEAN;
    signal ap_enable_operation_156 : BOOLEAN;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_1284_p00 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_1284_p10 : STD_LOGIC_VECTOR (8 downto 0);
    signal grp_fu_1284_p30 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_fu_1294_p10 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_1302_p10 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_1302_p20 : STD_LOGIC_VECTOR (24 downto 0);
    signal r_V_52_1_1_fu_1278_p10 : STD_LOGIC_VECTOR (20 downto 0);
    signal ap_condition_1038 : BOOLEAN;

    component sobel_hls_mux_32_hbi IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component sobel_hls_mul_mulibs IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (13 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (20 downto 0) );
    end component;


    component sobel_hls_ama_addjbC IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (10 downto 0);
        din3 : IN STD_LOGIC_VECTOR (23 downto 0);
        dout : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;


    component sobel_hls_mac_mulkbM IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (10 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (20 downto 0);
        dout : OUT STD_LOGIC_VECTOR (20 downto 0) );
    end component;


    component sobel_hls_mac_mullbW IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (10 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (23 downto 0);
        dout : OUT STD_LOGIC_VECTOR (24 downto 0) );
    end component;


    component Filter2D_1_k_buf_eOg IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0);
        address1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce1 : IN STD_LOGIC;
        we1 : IN STD_LOGIC;
        d1 : IN STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    k_buf_0_val_3_U : component Filter2D_1_k_buf_eOg
    generic map (
        DataWidth => 8,
        AddressRange => 1280,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_3_address0,
        ce0 => k_buf_0_val_3_ce0,
        q0 => k_buf_0_val_3_q0,
        address1 => k_buf_0_val_3_address1,
        ce1 => k_buf_0_val_3_ce1,
        we1 => k_buf_0_val_3_we1,
        d1 => p_src_data_stream_V_dout);

    k_buf_0_val_4_U : component Filter2D_1_k_buf_eOg
    generic map (
        DataWidth => 8,
        AddressRange => 1280,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_4_address0,
        ce0 => k_buf_0_val_4_ce0,
        q0 => k_buf_0_val_4_q0,
        address1 => k_buf_0_val_4_address1,
        ce1 => k_buf_0_val_4_ce1,
        we1 => k_buf_0_val_4_we1,
        d1 => k_buf_0_val_4_d1);

    k_buf_0_val_5_U : component Filter2D_1_k_buf_eOg
    generic map (
        DataWidth => 8,
        AddressRange => 1280,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => k_buf_0_val_5_address0,
        ce0 => k_buf_0_val_5_ce0,
        q0 => k_buf_0_val_5_q0,
        address1 => k_buf_0_val_5_address1,
        ce1 => k_buf_0_val_5_ce1,
        we1 => k_buf_0_val_5_we1,
        d1 => k_buf_0_val_5_d1);

    sobel_hls_mux_32_hbi_U31 : component sobel_hls_mux_32_hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => right_border_buf_0_s_fu_190,
        din1 => right_border_buf_0_1_fu_194,
        din2 => ap_const_lv8_0,
        din3 => col_assign_6_t_reg_1481,
        dout => tmp_28_fu_793_p5);

    sobel_hls_mux_32_hbi_U32 : component sobel_hls_mux_32_hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => right_border_buf_0_3_fu_202,
        din1 => right_border_buf_0_4_fu_206,
        din2 => ap_const_lv8_0,
        din3 => col_assign_6_t_reg_1481,
        dout => tmp_30_fu_811_p5);

    sobel_hls_mux_32_hbi_U33 : component sobel_hls_mux_32_hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => right_border_buf_0_5_fu_210,
        din1 => right_border_buf_0_2_fu_198,
        din2 => ap_const_lv8_0,
        din3 => col_assign_6_t_reg_1481,
        dout => tmp_31_fu_829_p5);

    sobel_hls_mux_32_hbi_U34 : component sobel_hls_mux_32_hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => col_buf_0_val_0_0_fu_804_p3,
        din1 => col_buf_0_val_1_0_fu_822_p3,
        din2 => col_buf_0_val_2_0_fu_840_p3,
        din3 => row_assign_13_0_t_reg_1426,
        dout => tmp_32_fu_883_p5);

    sobel_hls_mux_32_hbi_U35 : component sobel_hls_mux_32_hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => col_buf_0_val_0_0_fu_804_p3,
        din1 => col_buf_0_val_1_0_fu_822_p3,
        din2 => col_buf_0_val_2_0_fu_840_p3,
        din3 => row_assign_13_1_t_reg_1431,
        dout => tmp_33_fu_901_p5);

    sobel_hls_mux_32_hbi_U36 : component sobel_hls_mux_32_hbi
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 8,
        din3_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => col_buf_0_val_0_0_fu_804_p3,
        din1 => col_buf_0_val_1_0_fu_822_p3,
        din2 => col_buf_0_val_2_0_fu_840_p3,
        din3 => row_assign_13_2_t_reg_1436,
        dout => tmp_34_fu_919_p5);

    sobel_hls_mul_mulibs_U37 : component sobel_hls_mul_mulibs
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 14,
        din1_WIDTH => 8,
        dout_WIDTH => 21)
    port map (
        din0 => r_V_52_1_1_fu_1278_p0,
        din1 => r_V_52_1_1_fu_1278_p1,
        dout => r_V_52_1_1_fu_1278_p2);

    sobel_hls_ama_addjbC_U38 : component sobel_hls_ama_addjbC
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 11,
        din3_WIDTH => 24,
        dout_WIDTH => 25)
    port map (
        din0 => grp_fu_1284_p0,
        din1 => grp_fu_1284_p1,
        din2 => grp_fu_1284_p2,
        din3 => grp_fu_1284_p3,
        dout => grp_fu_1284_p4);

    sobel_hls_mac_mulkbM_U39 : component sobel_hls_mac_mulkbM
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 11,
        din1_WIDTH => 8,
        din2_WIDTH => 21,
        dout_WIDTH => 21)
    port map (
        din0 => grp_fu_1294_p0,
        din1 => grp_fu_1294_p1,
        din2 => r_V_52_1_1_reg_1518,
        dout => grp_fu_1294_p3);

    sobel_hls_mac_mullbW_U40 : component sobel_hls_mac_mullbW
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 11,
        din1_WIDTH => 8,
        din2_WIDTH => 24,
        dout_WIDTH => 25)
    port map (
        din0 => grp_fu_1302_p0,
        din1 => grp_fu_1302_p1,
        din2 => grp_fu_1302_p2,
        dout => grp_fu_1302_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((exitcond460_i_fu_610_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((exitcond461_i_fu_318_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter2_state5)) then 
                        ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter1;
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                elsif (((exitcond461_i_fu_318_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    t_V_2_reg_303_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond460_i_fu_610_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                t_V_2_reg_303 <= j_V_fu_616_p2;
            elsif (((exitcond461_i_fu_318_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                t_V_2_reg_303 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;

    t_V_reg_292_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                t_V_reg_292 <= i_V_reg_1392;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                t_V_reg_292 <= ap_const_lv10_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond460_i_fu_610_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                brmerge_reg_1464 <= brmerge_fu_750_p2;
                or_cond_i_i_reg_1450 <= or_cond_i_i_fu_664_p2;
                or_cond_i_reg_1471 <= or_cond_i_fu_755_p2;
                tmp_43_reg_1459 <= tmp_43_fu_746_p1;
                x_reg_1454 <= x_fu_738_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                brmerge_reg_1464_pp0_iter1_reg <= brmerge_reg_1464;
                exitcond460_i_reg_1441 <= exitcond460_i_fu_610_p2;
                exitcond460_i_reg_1441_pp0_iter1_reg <= exitcond460_i_reg_1441;
                or_cond_i_i_reg_1450_pp0_iter1_reg <= or_cond_i_i_reg_1450;
                or_cond_i_reg_1471_pp0_iter1_reg <= or_cond_i_reg_1471;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond460_i_reg_1441 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                col_assign_6_t_reg_1481 <= col_assign_6_t_fu_770_p2;
                k_buf_0_val_3_addr_reg_1475 <= tmp_26_fu_763_p1(11 - 1 downto 0);
                k_buf_0_val_4_addr_reg_1488 <= tmp_26_fu_763_p1(11 - 1 downto 0);
                k_buf_0_val_5_addr_reg_1494 <= tmp_26_fu_763_p1(11 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                exitcond460_i_reg_1441_pp0_iter2_reg <= exitcond460_i_reg_1441_pp0_iter1_reg;
                or_cond_i_reg_1471_pp0_iter2_reg <= or_cond_i_reg_1471_pp0_iter1_reg;
                or_cond_i_reg_1471_pp0_iter3_reg <= or_cond_i_reg_1471_pp0_iter2_reg;
                or_cond_i_reg_1471_pp0_iter4_reg <= or_cond_i_reg_1471_pp0_iter3_reg;
                src_kernel_win_0_va_6_reg_1500_pp0_iter3_reg <= src_kernel_win_0_va_6_reg_1500;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_V_reg_1392 <= i_V_fu_324_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond461_i_fu_318_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                icmp_reg_1406 <= icmp_fu_352_p2;
                row_assign_13_0_t_reg_1426 <= row_assign_13_0_t_fu_524_p2;
                row_assign_13_1_t_reg_1431 <= row_assign_13_1_t_fu_562_p2;
                row_assign_13_2_t_reg_1436 <= row_assign_13_2_t_fu_600_p2;
                tmp_2_reg_1411 <= tmp_2_fu_358_p2;
                tmp_3_reg_1419 <= tmp_3_fu_370_p2;
                tmp_424_0_not_reg_1401 <= tmp_424_0_not_fu_336_p2;
                tmp_468_1_reg_1415 <= tmp_468_1_fu_364_p2;
                tmp_s_reg_1397 <= tmp_s_fu_330_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_cond_i_reg_1471_pp0_iter3_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                p_Val2_1_reg_1555 <= p_Val2_s_fu_1189_p2(21 downto 14);
                p_Val2_s_reg_1550 <= p_Val2_s_fu_1189_p2;
                tmp_35_reg_1565 <= p_Val2_s_fu_1189_p2(26 downto 22);
                tmp_46_reg_1560 <= p_Val2_s_fu_1189_p2(13 downto 13);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_cond_i_reg_1471_pp0_iter1_reg = ap_const_lv1_1) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                r_V_52_1_1_reg_1518 <= r_V_52_1_1_fu_1278_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((tmp_s_reg_1397 = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_1) and (or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                right_border_buf_0_1_fu_194 <= right_border_buf_0_s_fu_190;
                right_border_buf_0_2_fu_198 <= right_border_buf_0_5_fu_210;
                right_border_buf_0_3_fu_202 <= col_buf_0_val_1_0_fu_822_p3;
                right_border_buf_0_4_fu_206 <= right_border_buf_0_3_fu_202;
                right_border_buf_0_5_fu_210 <= col_buf_0_val_2_0_fu_840_p3;
                right_border_buf_0_s_fu_190 <= col_buf_0_val_0_0_fu_804_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_cond_i_reg_1471_pp0_iter2_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                src_kernel_win_0_va_12_reg_1534 <= src_kernel_win_0_va_3_fu_178;
                src_kernel_win_0_va_9_reg_1528 <= src_kernel_win_0_va_fu_166;
                tmp3_reg_1545 <= tmp3_fu_1055_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                src_kernel_win_0_va_16_reg_1523 <= src_kernel_win_0_va_2_fu_174;
                src_kernel_win_0_va_6_reg_1500 <= src_kernel_win_0_va_6_fu_894_p3;
                src_kernel_win_0_va_7_reg_1506 <= src_kernel_win_0_va_7_fu_912_p3;
                src_kernel_win_0_va_8_reg_1512 <= src_kernel_win_0_va_8_fu_930_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond460_i_reg_1441_pp0_iter2_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                src_kernel_win_0_va_1_fu_170 <= src_kernel_win_0_va_fu_166;
                src_kernel_win_0_va_3_fu_178 <= src_kernel_win_0_va_16_reg_1523;
                src_kernel_win_0_va_4_fu_182 <= src_kernel_win_0_va_8_reg_1512;
                src_kernel_win_0_va_5_fu_186 <= src_kernel_win_0_va_4_fu_182;
                src_kernel_win_0_va_fu_166 <= src_kernel_win_0_va_6_reg_1500;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                src_kernel_win_0_va_2_fu_174 <= src_kernel_win_0_va_7_fu_912_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((or_cond_i_reg_1471_pp0_iter2_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                sum_V_0_2_reg_1540 <= grp_fu_1284_p4;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter5, exitcond461_i_fu_318_p2, ap_CS_fsm_state2, ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((exitcond461_i_fu_318_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0))) and not(((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ImagLoc_x_fu_638_p2 <= std_logic_vector(signed(ap_const_lv12_FFF) + signed(t_V_3_cast_fu_606_p1));
    Range1_all_zeros_fu_1231_p2 <= "1" when (tmp_35_reg_1565 = ap_const_lv5_0) else "0";
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state9 <= ap_CS_fsm(3);

    ap_block_pp0_assign_proc : process(ap_CS_fsm, ap_block_pp0_stage0_subdone)
    begin
                ap_block_pp0 <= ((ap_ST_fsm_pp0_stage0 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage0_subdone));
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(p_src_data_stream_V_empty_n, p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter5, or_cond_i_reg_1471_pp0_iter4_reg, ap_predicate_op147_read_state5, ap_predicate_op158_read_state5)
    begin
                ap_block_pp0_stage0_01001 <= (((or_cond_i_reg_1471_pp0_iter4_reg = ap_const_lv1_1) and (p_dst_data_stream_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op158_read_state5 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op147_read_state5 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(p_src_data_stream_V_empty_n, p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter5, or_cond_i_reg_1471_pp0_iter4_reg, ap_predicate_op147_read_state5, ap_predicate_op158_read_state5)
    begin
                ap_block_pp0_stage0_11001 <= (((or_cond_i_reg_1471_pp0_iter4_reg = ap_const_lv1_1) and (p_dst_data_stream_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op158_read_state5 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op147_read_state5 = ap_const_boolean_1)))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(p_src_data_stream_V_empty_n, p_dst_data_stream_V_full_n, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter5, or_cond_i_reg_1471_pp0_iter4_reg, ap_predicate_op147_read_state5, ap_predicate_op158_read_state5)
    begin
                ap_block_pp0_stage0_subdone <= (((or_cond_i_reg_1471_pp0_iter4_reg = ap_const_lv1_1) and (p_dst_data_stream_V_full_n = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op158_read_state5 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op147_read_state5 = ap_const_boolean_1)))));
    end process;

        ap_block_state3_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state5_pp0_stage0_iter2_assign_proc : process(p_src_data_stream_V_empty_n, ap_predicate_op147_read_state5, ap_predicate_op158_read_state5)
    begin
                ap_block_state5_pp0_stage0_iter2 <= (((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op158_read_state5 = ap_const_boolean_1)) or ((p_src_data_stream_V_empty_n = ap_const_logic_0) and (ap_predicate_op147_read_state5 = ap_const_boolean_1)));
    end process;

        ap_block_state6_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state8_pp0_stage0_iter5_assign_proc : process(p_dst_data_stream_V_full_n, or_cond_i_reg_1471_pp0_iter4_reg)
    begin
                ap_block_state8_pp0_stage0_iter5 <= ((or_cond_i_reg_1471_pp0_iter4_reg = ap_const_lv1_1) and (p_dst_data_stream_V_full_n = ap_const_logic_0));
    end process;


    ap_condition_1038_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, exitcond460_i_reg_1441_pp0_iter1_reg, or_cond_i_i_reg_1450_pp0_iter1_reg)
    begin
                ap_condition_1038 <= ((or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1));
    end process;


    ap_condition_pp0_exit_iter2_state5_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_condition_pp0_exit_iter2_state5 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter2_state5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, exitcond461_i_fu_318_p2, ap_CS_fsm_state2)
    begin
        if ((((exitcond461_i_fu_318_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_enable_operation_121_assign_proc : process(exitcond460_i_reg_1441)
    begin
                ap_enable_operation_121 <= (exitcond460_i_reg_1441 = ap_const_lv1_0);
    end process;


    ap_enable_operation_124_assign_proc : process(exitcond460_i_reg_1441)
    begin
                ap_enable_operation_124 <= (exitcond460_i_reg_1441 = ap_const_lv1_0);
    end process;


    ap_enable_operation_126_assign_proc : process(ap_predicate_op126_load_state4)
    begin
                ap_enable_operation_126 <= (ap_predicate_op126_load_state4 = ap_const_boolean_1);
    end process;


    ap_enable_operation_138_assign_proc : process(exitcond460_i_reg_1441_pp0_iter1_reg)
    begin
                ap_enable_operation_138 <= (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0);
    end process;


    ap_enable_operation_141_assign_proc : process(exitcond460_i_reg_1441_pp0_iter1_reg)
    begin
                ap_enable_operation_141 <= (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0);
    end process;


    ap_enable_operation_144_assign_proc : process(ap_predicate_op144_load_state5)
    begin
                ap_enable_operation_144 <= (ap_predicate_op144_load_state5 = ap_const_boolean_1);
    end process;


    ap_enable_operation_148_assign_proc : process(ap_predicate_op148_store_state5)
    begin
                ap_enable_operation_148 <= (ap_predicate_op148_store_state5 = ap_const_boolean_1);
    end process;


    ap_enable_operation_150_assign_proc : process(ap_predicate_op150_store_state5)
    begin
                ap_enable_operation_150 <= (ap_predicate_op150_store_state5 = ap_const_boolean_1);
    end process;


    ap_enable_operation_152_assign_proc : process(ap_predicate_op152_store_state5)
    begin
                ap_enable_operation_152 <= (ap_predicate_op152_store_state5 = ap_const_boolean_1);
    end process;


    ap_enable_operation_156_assign_proc : process(ap_predicate_op156_store_state5)
    begin
                ap_enable_operation_156 <= (ap_predicate_op156_store_state5 = ap_const_boolean_1);
    end process;


    ap_enable_operation_157_assign_proc : process(ap_predicate_op157_store_state5)
    begin
                ap_enable_operation_157 <= (ap_predicate_op157_store_state5 = ap_const_boolean_1);
    end process;


    ap_enable_operation_159_assign_proc : process(ap_predicate_op159_store_state5)
    begin
                ap_enable_operation_159 <= (ap_predicate_op159_store_state5 = ap_const_boolean_1);
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_enable_state4_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
                ap_enable_state4_pp0_iter1_stage0 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state5_pp0_iter2_stage0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_CS_fsm_pp0_stage0)
    begin
                ap_enable_state5_pp0_iter2_stage0 <= ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op126_load_state4_assign_proc : process(exitcond460_i_reg_1441, brmerge_reg_1464)
    begin
                ap_predicate_op126_load_state4 <= ((brmerge_reg_1464 = ap_const_lv1_1) and (exitcond460_i_reg_1441 = ap_const_lv1_0));
    end process;


    ap_predicate_op144_load_state5_assign_proc : process(exitcond460_i_reg_1441_pp0_iter1_reg, brmerge_reg_1464_pp0_iter1_reg)
    begin
                ap_predicate_op144_load_state5 <= ((brmerge_reg_1464_pp0_iter1_reg = ap_const_lv1_1) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op147_read_state5_assign_proc : process(exitcond460_i_reg_1441_pp0_iter1_reg, or_cond_i_i_reg_1450_pp0_iter1_reg, icmp_reg_1406)
    begin
                ap_predicate_op147_read_state5 <= ((or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_0) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op148_store_state5_assign_proc : process(exitcond460_i_reg_1441_pp0_iter1_reg, or_cond_i_i_reg_1450_pp0_iter1_reg, icmp_reg_1406, tmp_2_reg_1411)
    begin
                ap_predicate_op148_store_state5 <= ((tmp_2_reg_1411 = ap_const_lv1_1) and (or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_0) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op150_store_state5_assign_proc : process(exitcond460_i_reg_1441_pp0_iter1_reg, or_cond_i_i_reg_1450_pp0_iter1_reg, icmp_reg_1406, tmp_468_1_reg_1415)
    begin
                ap_predicate_op150_store_state5 <= ((tmp_468_1_reg_1415 = ap_const_lv1_1) and (or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_0) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op152_store_state5_assign_proc : process(exitcond460_i_reg_1441_pp0_iter1_reg, or_cond_i_i_reg_1450_pp0_iter1_reg, icmp_reg_1406, tmp_2_reg_1411)
    begin
                ap_predicate_op152_store_state5 <= ((tmp_2_reg_1411 = ap_const_lv1_1) and (or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_0) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op156_store_state5_assign_proc : process(exitcond460_i_reg_1441_pp0_iter1_reg, or_cond_i_i_reg_1450_pp0_iter1_reg, icmp_reg_1406, tmp_s_reg_1397)
    begin
                ap_predicate_op156_store_state5 <= ((tmp_s_reg_1397 = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_1) and (or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op157_store_state5_assign_proc : process(exitcond460_i_reg_1441_pp0_iter1_reg, or_cond_i_i_reg_1450_pp0_iter1_reg, icmp_reg_1406, tmp_s_reg_1397)
    begin
                ap_predicate_op157_store_state5 <= ((tmp_s_reg_1397 = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_1) and (or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op158_read_state5_assign_proc : process(exitcond460_i_reg_1441_pp0_iter1_reg, or_cond_i_i_reg_1450_pp0_iter1_reg, icmp_reg_1406, tmp_s_reg_1397)
    begin
                ap_predicate_op158_read_state5 <= ((tmp_s_reg_1397 = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_1) and (or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op159_store_state5_assign_proc : process(exitcond460_i_reg_1441_pp0_iter1_reg, or_cond_i_i_reg_1450_pp0_iter1_reg, icmp_reg_1406, tmp_s_reg_1397)
    begin
                ap_predicate_op159_store_state5 <= ((tmp_s_reg_1397 = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_1) and (or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_ready_assign_proc : process(exitcond461_i_fu_318_p2, ap_CS_fsm_state2)
    begin
        if (((exitcond461_i_fu_318_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    brmerge_fu_750_p2 <= (tmp_424_0_not_reg_1401 or tmp_22_fu_658_p2);
    col_assign_6_t_fu_770_p2 <= (tmp_43_reg_1459 xor ap_const_lv2_3);
        col_assign_cast_fu_760_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(x_reg_1454),32));

    col_buf_0_val_0_0_fu_804_p3 <= 
        k_buf_0_val_3_q0 when (brmerge_reg_1464_pp0_iter1_reg(0) = '1') else 
        tmp_28_fu_793_p5;
    col_buf_0_val_1_0_fu_822_p3 <= 
        k_buf_0_val_4_q0 when (brmerge_reg_1464_pp0_iter1_reg(0) = '1') else 
        tmp_30_fu_811_p5;
    col_buf_0_val_2_0_fu_840_p3 <= 
        k_buf_0_val_5_q0 when (brmerge_reg_1464_pp0_iter1_reg(0) = '1') else 
        tmp_31_fu_829_p5;
    deleted_zeros_fu_1263_p2 <= (not_carry_1_fu_1257_p2 and Range1_all_zeros_fu_1231_p2);
    exitcond460_i_fu_610_p2 <= "1" when (t_V_2_reg_303 = ap_const_lv11_502) else "0";
    exitcond461_i_fu_318_p2 <= "1" when (t_V_reg_292 = ap_const_lv10_2D2) else "0";
    grp_fu_1284_p0 <= grp_fu_1284_p00(8 - 1 downto 0);
    grp_fu_1284_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_8_reg_1512),9));
    grp_fu_1284_p1 <= grp_fu_1284_p10(8 - 1 downto 0);
    grp_fu_1284_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_5_fu_186),9));
    grp_fu_1284_p2 <= ap_const_lv19_3A8(11 - 1 downto 0);
    grp_fu_1284_p3 <= grp_fu_1284_p30(24 - 1 downto 0);
    grp_fu_1284_p30 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_V_52_0_1_cast_fu_1001_p1),25));
    grp_fu_1294_p0 <= ap_const_lv19_3A8(11 - 1 downto 0);
    grp_fu_1294_p1 <= grp_fu_1294_p10(8 - 1 downto 0);
    grp_fu_1294_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_1_fu_170),19));
    grp_fu_1302_p0 <= ap_const_lv19_3A8(11 - 1 downto 0);
    grp_fu_1302_p1 <= grp_fu_1302_p10(8 - 1 downto 0);
    grp_fu_1302_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_6_reg_1500_pp0_iter3_reg),19));
    grp_fu_1302_p2 <= grp_fu_1302_p20(24 - 1 downto 0);
    grp_fu_1302_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_V_52_2_1_cast_fu_1175_p1),25));
    i_V_fu_324_p2 <= std_logic_vector(unsigned(t_V_reg_292) + unsigned(ap_const_lv10_1));
    icmp1_fu_632_p2 <= "0" when (tmp_40_fu_622_p4 = ap_const_lv10_0) else "1";
    icmp_fu_352_p2 <= "0" when (tmp_6_fu_342_p4 = ap_const_lv9_0) else "1";
    j_V_fu_616_p2 <= std_logic_vector(unsigned(t_V_2_reg_303) + unsigned(ap_const_lv11_1));
    k_buf_0_val_3_address0 <= tmp_26_fu_763_p1(11 - 1 downto 0);
    k_buf_0_val_3_address1 <= k_buf_0_val_3_addr_reg_1475;

    k_buf_0_val_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_3_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_3_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, exitcond460_i_reg_1441_pp0_iter1_reg, or_cond_i_i_reg_1450_pp0_iter1_reg, icmp_reg_1406, tmp_s_reg_1397, tmp_2_reg_1411, ap_block_pp0_stage0_11001)
    begin
        if ((((tmp_s_reg_1397 = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_1) and (or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_2_reg_1411 = ap_const_lv1_1) and (or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_0) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            k_buf_0_val_3_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_3_we1_assign_proc : process(ap_enable_reg_pp0_iter2, exitcond460_i_reg_1441_pp0_iter1_reg, or_cond_i_i_reg_1450_pp0_iter1_reg, icmp_reg_1406, tmp_s_reg_1397, tmp_2_reg_1411, ap_block_pp0_stage0_11001)
    begin
        if ((((tmp_s_reg_1397 = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_1) and (or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_2_reg_1411 = ap_const_lv1_1) and (or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_0) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            k_buf_0_val_3_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_3_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_4_address0 <= tmp_26_fu_763_p1(11 - 1 downto 0);
    k_buf_0_val_4_address1 <= k_buf_0_val_4_addr_reg_1488;

    k_buf_0_val_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_4_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_4_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, exitcond460_i_reg_1441_pp0_iter1_reg, or_cond_i_i_reg_1450_pp0_iter1_reg, icmp_reg_1406, tmp_s_reg_1397, tmp_468_1_reg_1415, ap_block_pp0_stage0_11001)
    begin
        if ((((tmp_s_reg_1397 = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_1) and (or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_468_1_reg_1415 = ap_const_lv1_1) and (or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_0) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            k_buf_0_val_4_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_4_d1_assign_proc : process(p_src_data_stream_V_dout, icmp_reg_1406, tmp_s_reg_1397, tmp_468_1_reg_1415, k_buf_0_val_3_q0, ap_condition_1038)
    begin
        if ((ap_const_boolean_1 = ap_condition_1038)) then
            if (((tmp_s_reg_1397 = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_1))) then 
                k_buf_0_val_4_d1 <= k_buf_0_val_3_q0;
            elsif (((tmp_468_1_reg_1415 = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_0))) then 
                k_buf_0_val_4_d1 <= p_src_data_stream_V_dout;
            else 
                k_buf_0_val_4_d1 <= "XXXXXXXX";
            end if;
        else 
            k_buf_0_val_4_d1 <= "XXXXXXXX";
        end if; 
    end process;


    k_buf_0_val_4_we1_assign_proc : process(ap_enable_reg_pp0_iter2, exitcond460_i_reg_1441_pp0_iter1_reg, or_cond_i_i_reg_1450_pp0_iter1_reg, icmp_reg_1406, tmp_s_reg_1397, tmp_468_1_reg_1415, ap_block_pp0_stage0_11001)
    begin
        if ((((tmp_s_reg_1397 = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_1) and (or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_468_1_reg_1415 = ap_const_lv1_1) and (or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_0) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            k_buf_0_val_4_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_4_we1 <= ap_const_logic_0;
        end if; 
    end process;

    k_buf_0_val_5_address0 <= tmp_26_fu_763_p1(11 - 1 downto 0);
    k_buf_0_val_5_address1 <= k_buf_0_val_5_addr_reg_1494;

    k_buf_0_val_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            k_buf_0_val_5_ce0 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_5_ce1_assign_proc : process(ap_enable_reg_pp0_iter2, exitcond460_i_reg_1441_pp0_iter1_reg, or_cond_i_i_reg_1450_pp0_iter1_reg, icmp_reg_1406, tmp_s_reg_1397, tmp_2_reg_1411, ap_block_pp0_stage0_11001)
    begin
        if ((((tmp_s_reg_1397 = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_1) and (or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_2_reg_1411 = ap_const_lv1_1) and (or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_0) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            k_buf_0_val_5_ce1 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    k_buf_0_val_5_d1_assign_proc : process(p_src_data_stream_V_dout, icmp_reg_1406, tmp_s_reg_1397, tmp_2_reg_1411, k_buf_0_val_4_q0, ap_condition_1038)
    begin
        if ((ap_const_boolean_1 = ap_condition_1038)) then
            if (((tmp_s_reg_1397 = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_1))) then 
                k_buf_0_val_5_d1 <= k_buf_0_val_4_q0;
            elsif (((tmp_2_reg_1411 = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_0))) then 
                k_buf_0_val_5_d1 <= p_src_data_stream_V_dout;
            else 
                k_buf_0_val_5_d1 <= "XXXXXXXX";
            end if;
        else 
            k_buf_0_val_5_d1 <= "XXXXXXXX";
        end if; 
    end process;


    k_buf_0_val_5_we1_assign_proc : process(ap_enable_reg_pp0_iter2, exitcond460_i_reg_1441_pp0_iter1_reg, or_cond_i_i_reg_1450_pp0_iter1_reg, icmp_reg_1406, tmp_s_reg_1397, tmp_2_reg_1411, ap_block_pp0_stage0_11001)
    begin
        if ((((tmp_s_reg_1397 = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_1) and (or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((tmp_2_reg_1411 = ap_const_lv1_1) and (or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_0) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            k_buf_0_val_5_we1 <= ap_const_logic_1;
        else 
            k_buf_0_val_5_we1 <= ap_const_logic_0;
        end if; 
    end process;

    not_carry_1_fu_1257_p2 <= (tmp_48_fu_1249_p3 or rev2_fu_1243_p2);
    or_cond_i496_i_fu_412_p2 <= (tmp_7_fu_406_p2 and rev_fu_400_p2);
    or_cond_i_fu_755_p2 <= (icmp_reg_1406 and icmp1_fu_632_p2);
    or_cond_i_i_fu_664_p2 <= (tmp_22_fu_658_p2 and rev1_fu_652_p2);
    p_Val2_2_fu_1226_p2 <= std_logic_vector(unsigned(tmp_6_i_i_cast_fu_1223_p1) + unsigned(p_Val2_1_reg_1555));
    p_Val2_s_fu_1189_p2 <= std_logic_vector(unsigned(sum_V_2_cast_fu_1143_p1) + unsigned(tmp5_cast_fu_1186_p1));
    p_assign_14_1_fu_456_p2 <= std_logic_vector(signed(ap_const_lv11_7FE) + signed(t_V_cast_fu_314_p1));
    p_assign_14_2_fu_482_p2 <= std_logic_vector(signed(ap_const_lv11_7FD) + signed(t_V_cast_fu_314_p1));
    p_assign_1_fu_450_p2 <= std_logic_vector(signed(ap_const_lv2_2) - signed(tmp_12_fu_440_p1));
    p_assign_3_fu_678_p2 <= std_logic_vector(unsigned(ap_const_lv12_1) - unsigned(t_V_3_cast_fu_606_p1));
    p_assign_4_fu_702_p2 <= std_logic_vector(signed(ap_const_lv12_9FE) - signed(p_p2_i_i_fu_684_p3));
    p_assign_5_fu_708_p3 <= 
        ImagLoc_x_fu_638_p2 when (or_cond_i_i_fu_664_p2(0) = '1') else 
        p_assign_4_fu_702_p2;
    p_assign_s_fu_426_p2 <= std_logic_vector(unsigned(ap_const_lv11_1) - unsigned(t_V_cast_fu_314_p1));

    p_dst_data_stream_V_blk_n_assign_proc : process(p_dst_data_stream_V_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter5, or_cond_i_reg_1471_pp0_iter4_reg)
    begin
        if (((or_cond_i_reg_1471_pp0_iter4_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then 
            p_dst_data_stream_V_blk_n <= p_dst_data_stream_V_full_n;
        else 
            p_dst_data_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_dst_data_stream_V_din <= 
        p_Val2_2_fu_1226_p2 when (deleted_zeros_fu_1263_p2(0) = '1') else 
        ap_const_lv8_FF;

    p_dst_data_stream_V_write_assign_proc : process(ap_enable_reg_pp0_iter5, or_cond_i_reg_1471_pp0_iter4_reg, ap_block_pp0_stage0_11001)
    begin
        if (((or_cond_i_reg_1471_pp0_iter4_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            p_dst_data_stream_V_write <= ap_const_logic_1;
        else 
            p_dst_data_stream_V_write <= ap_const_logic_0;
        end if; 
    end process;

    p_p2_i497_i_fu_432_p3 <= 
        p_assign_s_fu_426_p2 when (tmp_11_fu_418_p3(0) = '1') else 
        tmp_5_fu_380_p2;
    p_p2_i497_i_p_assign_s_fu_508_p3 <= 
        tmp_12_fu_440_p1 when (tmp_9_fu_444_p2(0) = '1') else 
        p_assign_1_fu_450_p2;
        p_p2_i_i_cast_fu_692_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_p2_i_i_fu_684_p3),13));

    p_p2_i_i_fu_684_p3 <= 
        p_assign_3_fu_678_p2 when (tmp_42_fu_670_p3(0) = '1') else 
        ImagLoc_x_fu_638_p2;
    p_shl1_cast_fu_979_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl1_fu_971_p3),20));
    p_shl1_fu_971_p3 <= (src_kernel_win_0_va_4_fu_182 & ap_const_lv11_0);
    p_shl2_cast_fu_991_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl2_fu_983_p3),20));
    p_shl2_fu_983_p3 <= (src_kernel_win_0_va_4_fu_182 & ap_const_lv2_0);
    p_shl3_cast_fu_1099_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl3_fu_1092_p3),20));
    p_shl3_fu_1092_p3 <= (src_kernel_win_0_va_12_reg_1534 & ap_const_lv11_0);
    p_shl4_cast_fu_1110_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl4_fu_1103_p3),20));
    p_shl4_fu_1103_p3 <= (src_kernel_win_0_va_12_reg_1534 & ap_const_lv2_0);
    p_shl5_cast_fu_1019_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl5_fu_1012_p3),20));
    p_shl5_fu_1012_p3 <= (src_kernel_win_0_va_7_reg_1506 & ap_const_lv11_0);
    p_shl6_cast_fu_1030_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl6_fu_1023_p3),20));
    p_shl6_fu_1023_p3 <= (src_kernel_win_0_va_7_reg_1506 & ap_const_lv2_0);
    p_shl7_cast_fu_1165_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl7_fu_1158_p3),20));
    p_shl7_fu_1158_p3 <= (src_kernel_win_0_va_9_reg_1528 & ap_const_lv2_0);
    p_shl_cast_fu_1154_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl_fu_1147_p3),20));
    p_shl_fu_1147_p3 <= (src_kernel_win_0_va_9_reg_1528 & ap_const_lv11_0);

    p_src_data_stream_V_blk_n_assign_proc : process(p_src_data_stream_V_empty_n, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, exitcond460_i_reg_1441_pp0_iter1_reg, or_cond_i_i_reg_1450_pp0_iter1_reg, icmp_reg_1406, tmp_s_reg_1397)
    begin
        if ((((tmp_s_reg_1397 = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_1) and (or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((or_cond_i_i_reg_1450_pp0_iter1_reg = ap_const_lv1_1) and (icmp_reg_1406 = ap_const_lv1_0) and (exitcond460_i_reg_1441_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)))) then 
            p_src_data_stream_V_blk_n <= p_src_data_stream_V_empty_n;
        else 
            p_src_data_stream_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    p_src_data_stream_V_read_assign_proc : process(ap_enable_reg_pp0_iter2, ap_predicate_op147_read_state5, ap_predicate_op158_read_state5, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_predicate_op158_read_state5 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_predicate_op147_read_state5 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            p_src_data_stream_V_read <= ap_const_logic_1;
        else 
            p_src_data_stream_V_read <= ap_const_logic_0;
        end if; 
    end process;

        r_V_52_0_1_cast_fu_1001_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_52_0_1_fu_995_p2),24));

    r_V_52_0_1_fu_995_p2 <= std_logic_vector(unsigned(p_shl1_cast_fu_979_p1) - unsigned(p_shl2_cast_fu_991_p1));
    r_V_52_1_1_fu_1278_p0 <= ap_const_lv21_1171(14 - 1 downto 0);
    r_V_52_1_1_fu_1278_p1 <= r_V_52_1_1_fu_1278_p10(8 - 1 downto 0);
    r_V_52_1_1_fu_1278_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(src_kernel_win_0_va_2_fu_174),21));
        r_V_52_1_2_cast_fu_1040_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_52_1_2_fu_1034_p2),24));

    r_V_52_1_2_fu_1034_p2 <= std_logic_vector(unsigned(p_shl5_cast_fu_1019_p1) - unsigned(p_shl6_cast_fu_1030_p1));
        r_V_52_1_cast_fu_1120_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_52_1_fu_1114_p2),24));

    r_V_52_1_fu_1114_p2 <= std_logic_vector(unsigned(p_shl3_cast_fu_1099_p1) - unsigned(p_shl4_cast_fu_1110_p1));
        r_V_52_2_1_cast_fu_1175_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(r_V_52_2_1_fu_1169_p2),24));

    r_V_52_2_1_fu_1169_p2 <= std_logic_vector(unsigned(p_shl_cast_fu_1154_p1) - unsigned(p_shl7_cast_fu_1165_p1));
    rev1_fu_652_p2 <= (tmp_41_fu_644_p3 xor ap_const_lv1_1);
    rev2_fu_1243_p2 <= (tmp_47_fu_1236_p3 xor ap_const_lv1_1);
    rev_fu_400_p2 <= (tmp_10_fu_392_p3 xor ap_const_lv1_1);
    row_assign_13_0_t_fu_524_p2 <= (y_fu_516_p3 xor ap_const_lv2_3);
    row_assign_13_1_t_fu_562_p2 <= (tmp_13_fu_554_p3 xor ap_const_lv2_3);
    row_assign_13_2_t_fu_600_p2 <= (tmp_18_fu_592_p3 xor ap_const_lv2_3);
    sel_tmp7_fu_726_p2 <= (tmp_41_fu_644_p3 or tmp_26_not_fu_720_p2);
    sel_tmp8_fu_732_p2 <= (tmp_23_fu_696_p2 and sel_tmp7_fu_726_p2);
    sel_tmp_cast_fu_716_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_assign_5_fu_708_p3),13));
    src_kernel_win_0_va_6_fu_894_p3 <= 
        tmp_32_fu_883_p5 when (tmp_3_reg_1419(0) = '1') else 
        col_buf_0_val_0_0_fu_804_p3;
    src_kernel_win_0_va_7_fu_912_p3 <= 
        tmp_33_fu_901_p5 when (tmp_3_reg_1419(0) = '1') else 
        col_buf_0_val_1_0_fu_822_p3;
    src_kernel_win_0_va_8_fu_930_p3 <= 
        tmp_34_fu_919_p5 when (tmp_3_reg_1419(0) = '1') else 
        col_buf_0_val_2_0_fu_840_p3;
    sum_V_0_2_cast_fu_1089_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sum_V_0_2_reg_1540),26));
    sum_V_2_cast_fu_1143_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(sum_V_2_fu_1137_p2),27));
    sum_V_2_fu_1137_p2 <= std_logic_vector(unsigned(tmp2_fu_1128_p2) + unsigned(tmp3_cast_fu_1134_p1));
    t_V_3_cast_fu_606_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_V_2_reg_303),12));
    t_V_cast_fu_314_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_V_reg_292),11));
    tmp2_fu_1128_p2 <= std_logic_vector(unsigned(tmp_510_1_cast_fu_1124_p1) + unsigned(sum_V_0_2_cast_fu_1089_p1));
    tmp3_cast_fu_1134_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp3_reg_1545),26));
    tmp3_fu_1055_p2 <= std_logic_vector(unsigned(tmp_510_1_2_cast_cas_fu_1044_p1) + unsigned(tmp4_cast_fu_1052_p1));
    tmp4_cast_fu_1052_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_1294_p3),25));
    tmp5_cast_fu_1186_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_1302_p3),27));
    tmp_10_fu_392_p3 <= tmp_5_fu_380_p2(10 downto 10);
    tmp_11_fu_418_p3 <= tmp_5_fu_380_p2(10 downto 10);
    tmp_12_fu_440_p1 <= p_p2_i497_i_fu_432_p3(2 - 1 downto 0);
    tmp_13_fu_554_p3 <= 
        tmp_4_fu_546_p3 when (tmp_14_fu_462_p3(0) = '1') else 
        tmp_1_fu_530_p2;
    tmp_14_fu_462_p3 <= p_assign_14_1_fu_456_p2(10 downto 10);
    tmp_15_fu_470_p3 <= p_assign_14_1_fu_456_p2(10 downto 10);
    tmp_16_fu_568_p2 <= std_logic_vector(unsigned(ap_const_lv2_1) + unsigned(tmp_8_fu_376_p1));
    tmp_17_fu_584_p3 <= 
        tmp_38_fu_574_p2 when (tmp_24_fu_496_p3(0) = '1') else 
        tmp_39_fu_580_p1;
    tmp_18_fu_592_p3 <= 
        tmp_17_fu_584_p3 when (tmp_21_fu_488_p3(0) = '1') else 
        tmp_16_fu_568_p2;
    tmp_1_fu_530_p2 <= (tmp_8_fu_376_p1 xor ap_const_lv2_2);
    tmp_20_fu_478_p1 <= t_V_reg_292(2 - 1 downto 0);
    tmp_21_fu_488_p3 <= p_assign_14_2_fu_482_p2(10 downto 10);
    tmp_22_fu_658_p2 <= "1" when (signed(ImagLoc_x_fu_638_p2) < signed(ap_const_lv12_500)) else "0";
    tmp_23_fu_696_p2 <= "1" when (signed(p_p2_i_i_fu_684_p3) < signed(ap_const_lv12_500)) else "0";
    tmp_24_fu_496_p3 <= p_assign_14_2_fu_482_p2(10 downto 10);
    tmp_25_fu_504_p1 <= t_V_reg_292(2 - 1 downto 0);
    tmp_26_fu_763_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_assign_cast_fu_760_p1),64));
    tmp_26_not_fu_720_p2 <= (tmp_22_fu_658_p2 xor ap_const_lv1_1);
    tmp_27_fu_536_p2 <= std_logic_vector(signed(ap_const_lv2_2) - signed(tmp_20_fu_478_p1));
    tmp_29_fu_542_p1 <= p_assign_14_1_fu_456_p2(2 - 1 downto 0);
    tmp_2_fu_358_p2 <= "1" when (t_V_reg_292 = ap_const_lv10_1) else "0";
    tmp_38_fu_574_p2 <= (tmp_25_fu_504_p1 xor ap_const_lv2_3);
    tmp_39_fu_580_p1 <= p_assign_14_2_fu_482_p2(2 - 1 downto 0);
    tmp_3_fu_370_p2 <= "1" when (unsigned(t_V_reg_292) > unsigned(ap_const_lv10_2D0)) else "0";
    tmp_40_fu_622_p4 <= t_V_2_reg_303(10 downto 1);
    tmp_41_fu_644_p3 <= ImagLoc_x_fu_638_p2(11 downto 11);
    tmp_424_0_not_fu_336_p2 <= (tmp_s_fu_330_p2 xor ap_const_lv1_1);
    tmp_42_fu_670_p3 <= ImagLoc_x_fu_638_p2(11 downto 11);
    tmp_43_fu_746_p1 <= x_fu_738_p3(2 - 1 downto 0);
    tmp_468_1_fu_364_p2 <= "1" when (t_V_reg_292 = ap_const_lv10_0) else "0";
    tmp_47_fu_1236_p3 <= p_Val2_s_reg_1550(21 downto 21);
    tmp_48_fu_1249_p3 <= p_Val2_2_fu_1226_p2(7 downto 7);
    tmp_4_fu_546_p3 <= 
        tmp_27_fu_536_p2 when (tmp_15_fu_470_p3(0) = '1') else 
        tmp_29_fu_542_p1;
    tmp_510_1_2_cast_cas_fu_1044_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_V_52_1_2_cast_fu_1040_p1),25));
    tmp_510_1_cast_fu_1124_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(r_V_52_1_cast_fu_1120_p1),26));
    tmp_5_fu_380_p2 <= std_logic_vector(signed(ap_const_lv11_7FF) + signed(t_V_cast_fu_314_p1));
    tmp_6_fu_342_p4 <= t_V_reg_292(9 downto 1);
    tmp_6_i_i_cast_fu_1223_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_46_reg_1560),8));
    tmp_72_cast_fu_386_p2 <= std_logic_vector(signed(ap_const_lv2_3) + signed(tmp_8_fu_376_p1));
    tmp_7_fu_406_p2 <= "1" when (signed(tmp_5_fu_380_p2) < signed(ap_const_lv11_2D0)) else "0";
    tmp_8_fu_376_p1 <= t_V_reg_292(2 - 1 downto 0);
    tmp_9_fu_444_p2 <= "1" when (signed(p_p2_i497_i_fu_432_p3) < signed(ap_const_lv11_2D0)) else "0";
    tmp_s_fu_330_p2 <= "1" when (unsigned(t_V_reg_292) < unsigned(ap_const_lv10_2D0)) else "0";
    x_fu_738_p3 <= 
        p_p2_i_i_cast_fu_692_p1 when (sel_tmp8_fu_732_p2(0) = '1') else 
        sel_tmp_cast_fu_716_p1;
    y_fu_516_p3 <= 
        tmp_72_cast_fu_386_p2 when (or_cond_i496_i_fu_412_p2(0) = '1') else 
        p_p2_i497_i_p_assign_s_fu_508_p3;
end behav;
